# Seed grapes from the grapes.js data
# Run with: rails db:seed:grapes

Grape.delete_all
ActiveRecord::Base.connection.reset_pk_sequence!('grapes')

grapes_data = [
  {
    name: "Cabernet Sauvignon",
    color: "red",
    origin_country: "France",
    main_regions: ["Bordeaux", "Napa Valley", "Maipo Valley", "Coonawarra", "Margaret River", "Stellenbosch", "Bolgheri"],
    synonyms: ["Cabernet", "Petit Cabernet", "Bordo"],
    is_blending_grape: true,
    notes: ["blackcurrant", "blackberry", "plum", "cedar", "tobacco", "mint", "graphite"],
    serving: "Great with grilled steak, roast lamb, beef stew, burgers, and aged hard cheeses.",
    relevance: 100,
  },
  {
    name: "Chardonnay",
    color: "white",
    origin_country: "France",
    main_regions: ["Burgundy", "Champagne", "California", "Australia", "Chile", "South Africa", "New Zealand"],
    synonyms: ["Morillon", "Aubaine", "Melon d'Arbois"],
    is_blending_grape: true,
    notes: ["apple", "lemon", "pear", "peach", "acacia", "butter", "vanilla", "almond"],
    serving: "Great with roast chicken, grilled salmon, creamy pasta, shellfish, and soft cheeses.",
    relevance: 98,
  },
  {
    name: "Merlot",
    color: "red",
    origin_country: "France",
    main_regions: ["Bordeaux", "Pomerol", "Saint-Émilion", "Napa Valley", "Sonoma", "Chile", "Australia"],
    synonyms: ["Merlau", "Picard"],
    is_blending_grape: true,
    notes: ["plum", "black cherry", "blackberry", "chocolate", "vanilla", "herbs"],
    serving: "Great with roast chicken, duck, pork, burgers, pizza, and mild cheeses.",
    relevance: 95,
  },
  {
    name: "Pinot Noir",
    color: "red",
    origin_country: "France",
    main_regions: ["Burgundy", "Champagne", "Oregon", "California", "Central Otago", "Yarra Valley", "Tasmania"],
    synonyms: ["Spätburgunder", "Blauburgunder", "Pinot Nero"],
    is_blending_grape: true,
    notes: ["cherry", "raspberry", "strawberry", "violet", "earth", "mushroom", "clove"],
    serving: "Great with roast chicken, mushrooms, salmon, duck, and charcuterie.",
    relevance: 92,
  },
  {
    name: "Sauvignon Blanc",
    color: "white",
    origin_country: "France",
    main_regions: ["Loire Valley", "Bordeaux", "Marlborough", "Napa Valley", "Casablanca Valley", "Adelaide Hills"],
    synonyms: ["Fumé Blanc", "Sauvignon"],
    is_blending_grape: true,
    notes: ["lime", "grapefruit", "passionfruit", "green apple", "grass", "herbs", "gooseberry"],
    serving: "Great with oysters, goat cheese, salads, asparagus, fresh seafood, and Thai cuisine.",
    relevance: 88,
  },
  {
    name: "Syrah",
    color: "red",
    origin_country: "France",
    main_regions: ["Northern Rhône", "Barossa Valley", "McLaren Vale", "Hunter Valley", "Washington State", "Central Coast"],
    synonyms: ["Shiraz", "Hermitage", "Marsanne Noire"],
    is_blending_grape: true,
    notes: ["blackberry", "black plum", "black pepper", "violet", "smoke", "olive", "spice"],
    serving: "Great with barbecue, grilled lamb, beef stew, sausages, roasted vegetables, and spicy food.",
    relevance: 85,
  },
  {
    name: "Sangiovese",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Tuscany", "Chianti", "Brunello di Montalcino", "Montepulciano", "Umbria", "California"],
    synonyms: ["Brunello", "Prugnolo Gentile", "Morellino"],
    is_blending_grape: true,
    notes: ["cherry", "red plum", "violet", "dried herbs", "earth", "leather", "tomato leaf"],
    serving: "Great with tomato pasta, pizza, roast pork, grilled meats, and aged cheeses.",
    relevance: 83,
  },
  {
    name: "Tempranillo",
    color: "red",
    origin_country: "Spain",
    main_regions: ["Rioja", "Ribera del Duero", "Toro", "La Mancha", "Portugal", "Argentina"],
    synonyms: ["Tinta del País", "Tinta Roriz", "Aragonez", "Cencibel"],
    is_blending_grape: true,
    notes: ["plum", "cherry", "strawberry", "leather", "tobacco", "vanilla", "cedar"],
    serving: "Great with lamb, roast pork, tapas, chorizo, grilled meats, and aged Manchego.",
    relevance: 82,
  },
  {
    name: "Riesling",
    color: "white",
    origin_country: "Germany",
    main_regions: ["Mosel", "Rheingau", "Alsace", "Clare Valley", "Eden Valley", "Washington State", "Austria"],
    synonyms: ["Rhine Riesling", "Rheinriesling", "Johannisberg Riesling"],
    is_blending_grape: false,
    notes: ["lime", "lemon", "green apple", "white flowers", "peach", "flint", "petrol"],
    serving: "Great with spicy Asian food, pork, seafood, Thai cuisine, roast chicken, and spicy sausages.",
    relevance: 80,
  },
  {
    name: "Grenache",
    color: "red",
    origin_country: "Spain",
    main_regions: ["Aragon", "Priorat", "Rhône Valley", "Châteauneuf-du-Pape", "Barossa Valley", "McLaren Vale"],
    synonyms: ["Garnacha", "Grenache Noir", "Cannonau", "Alicante"],
    is_blending_grape: true,
    notes: ["raspberry", "strawberry", "red plum", "blackberry", "white pepper", "herbs", "spice"],
    serving: "Great with roast lamb, grilled vegetables, stews, charcuterie, and Mediterranean food.",
    relevance: 78,
  },
  {
    name: "Garnacha",
    color: "red",
    origin_country: "Spain",
    main_regions: ["Aragon", "Priorat", "Rioja", "Navarra", "Catalonia"],
    synonyms: ["Grenache", "Garnacha Tinta", "Cannonau"],
    is_blending_grape: true,
    notes: ["raspberry", "strawberry", "red plum", "blackberry", "pepper", "spice"],
    serving: "Great with lamb, roast pork, Mediterranean dishes, charcuterie, and grilled vegetables.",
    relevance: 78,
  },
  {
    name: "Nebbiolo",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Piedmont", "Barolo", "Barbaresco", "Langhe", "Lombardy"],
    synonyms: ["Spanna", "Chiavennasca", "Picoutener"],
    is_blending_grape: false,
    notes: ["cherry", "raspberry", "rose", "violet", "tar", "leather", "licorice"],
    serving: "Great with braised beef, truffles, wild game, mushroom dishes, and aged cheeses.",
    relevance: 77,
  },
  {
    name: "Malbec",
    color: "red",
    origin_country: "France",
    main_regions: ["Mendoza", "Cahors", "Salta", "Uco Valley", "Luján de Cuyo", "South Australia"],
    synonyms: ["Côt", "Cot", "Auxerrois", "Pressac"],
    is_blending_grape: true,
    notes: ["blackberry", "plum", "blueberry", "violet", "chocolate", "tobacco", "leather"],
    serving: "Great with steak, barbecue, lamb, sausages, burgers, and grilled vegetables.",
    relevance: 75,
  },
  {
    name: "Trebbiano",
    color: "white",
    origin_country: "Italy",
    main_regions: ["Tuscany", "Umbria", "Abruzzo", "Emilia-Romagna", "France"],
    synonyms: ["Ugni Blanc", "Trebbiano Toscano", "Procanico"],
    is_blending_grape: true,
    notes: ["lemon", "green apple", "pear", "citrus", "almond", "herbs"],
    serving: "Great with seafood, salads, light pasta, poultry, and fresh cheeses.",
    relevance: 72,
  },
  {
    name: "Ugni Blanc",
    color: "white",
    origin_country: "Italy",
    main_regions: ["Cognac", "Armagnac", "Gascony", "Provence", "Tuscany"],
    synonyms: ["Trebbiano Toscano", "Saint-Émilion", "Rolle"],
    is_blending_grape: true,
    notes: ["lemon", "green apple", "pear", "citrus", "herbs", "minerals"],
    serving: "Great with seafood, oysters, salads, grilled fish, and light poultry dishes.",
    relevance: 72,
  },
  {
    name: "Pinot Gris",
    color: "white",
    origin_country: "France",
    main_regions: ["Alsace", "Friuli", "Veneto", "Oregon", "Germany", "New Zealand", "Australia"],
    synonyms: ["Pinot Grigio", "Grauburgunder", "Ruländer"],
    is_blending_grape: false,
    notes: ["pear", "apple", "peach", "citrus", "almond", "honey", "spice"],
    serving: "Great with seafood, light pasta, salads, fresh vegetables, poultry, and light Asian dishes.",
    relevance: 70,
  },
  {
    name: "Cabernet Franc",
    color: "red",
    origin_country: "France",
    main_regions: ["Loire Valley", "Bordeaux", "Napa Valley", "Tuscany", "Ontario"],
    synonyms: ["Bouchet", "Breton", "Bouchy"],
    is_blending_grape: true,
    notes: ["raspberry", "red currant", "violet", "bell pepper", "herbs", "graphite", "cedar"],
    serving: "Great with roast lamb, grilled vegetables, duck, charcuterie, and goat cheese.",
    relevance: 68,
  },
  {
    name: "Airén",
    color: "white",
    origin_country: "Spain",
    main_regions: ["La Mancha", "Valdepeñas", "Madrid"],
    synonyms: ["Lairén", "Forcallat Blanca", "Valdepeñas"],
    is_blending_grape: true,
    notes: ["apple", "pear", "citrus", "herbs", "almond"],
    serving: "Great with light tapas, salads, seafood, grilled vegetables, and simple poultry dishes.",
    relevance: 68,
  },
  {
    name: "Zinfandel",
    color: "red",
    origin_country: "Croatia",
    main_regions: ["California", "Napa Valley", "Sonoma", "Paso Robles", "Lodi"],
    synonyms: ["Primitivo", "Tribidrag", "Crljenak Kaštelanski"],
    is_blending_grape: true,
    notes: ["blackberry", "raspberry", "black pepper", "plum", "jam", "licorice", "spice"],
    serving: "Great with barbecue ribs, burgers, pizza, spicy sausages, and grilled meats.",
    relevance: 65,
  },
  {
    name: "Primitivo",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Puglia", "Manduria", "Salento", "California"],
    synonyms: ["Zinfandel", "Crljenak Kaštelanski"],
    is_blending_grape: true,
    notes: ["blackberry", "plum", "cherry", "jam", "black pepper", "chocolate"],
    serving: "Great with barbecue, burgers, grilled meats, spicy sausages, and rich pasta.",
    relevance: 65,
  },
  {
    name: "Chenin Blanc",
    color: "white",
    origin_country: "France",
    main_regions: ["Loire Valley", "Vouvray", "Savennières", "South Africa", "California", "Australia"],
    synonyms: ["Pineau de la Loire", "Steen"],
    is_blending_grape: true,
    notes: ["pear", "apple", "quince", "apricot", "honey", "chamomile", "wool"],
    serving: "Great with roast chicken, pork, goat cheese, creamy dishes, seafood, and spicy food.",
    relevance: 62,
  },
  {
    name: "Gamay",
    color: "red",
    origin_country: "France",
    main_regions: ["Beaujolais", "Beaujolais-Villages", "Loire Valley", "Oregon", "Canada"],
    synonyms: ["Gamay Noir", "Gamay Beaujolais"],
    is_blending_grape: false,
    notes: ["strawberry", "raspberry", "cherry", "banana", "violet", "pepper", "earth"],
    serving: "Great with charcuterie, roast chicken, pork, mushrooms, salads, and light cheeses.",
    relevance: 60,
  },
  {
    name: "Muscat",
    color: "white",
    origin_country: "Greece",
    main_regions: ["France", "Italy", "Greece", "Australia", "Austria", "Spain"],
    synonyms: ["Muscat Blanc à Petits Grains", "Moscato", "Muscat Canelli"],
    is_blending_grape: false,
    notes: ["grape", "orange blossom", "rose", "peach", "lychee", "honey", "citrus"],
    serving: "Great with fruit desserts, pastries, spicy Asian food, blue cheese, and fresh fruit.",
    relevance: 60,
  },
  {
    name: "Barbera",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Piedmont", "Alba", "Asti", "Monferrato", "California", "Argentina"],
    synonyms: ["Barbera del Monferrato", "Barbera Grossa"],
    is_blending_grape: true,
    notes: ["sour cherry", "red plum", "raspberry", "violet", "licorice", "spice"],
    serving: "Great with pizza, tomato pasta, antipasti, sausages, and roasted vegetables.",
    relevance: 58,
  },
  {
    name: "Albariño",
    color: "white",
    origin_country: "Spain",
    main_regions: ["Rías Baixas", "Galicia", "Vinho Verde", "Monção e Melgaço"],
    synonyms: ["Alvarinho", "Albarino"],
    is_blending_grape: false,
    notes: ["lemon", "lime", "peach", "pear", "white flowers", "saline", "citrus"],
    serving: "Great with oysters, shellfish, grilled fish, ceviche, sushi, and tapas.",
    relevance: 58,
  },
  {
    name: "Grüner Veltliner",
    color: "white",
    origin_country: "Austria",
    main_regions: ["Wachau", "Kamptal", "Kremstal", "Weinviertel", "Vienna"],
    synonyms: ["Grüner", "Weissgipfler"],
    is_blending_grape: false,
    notes: ["green apple", "lime", "white pepper", "herbs", "citrus", "minerals"],
    serving: "Great with schnitzel, vegetables, salads, seafood, sushi, and Asian cuisine.",
    relevance: 57,
  },
  {
    name: "Mourvèdre",
    color: "red",
    origin_country: "Spain",
    main_regions: ["Bandol", "Rhône Valley", "Languedoc", "Jumilla", "Yecla", "Barossa Valley"],
    synonyms: ["Monastrell", "Mataro", "Mourvèdre Noir"],
    is_blending_grape: true,
    notes: ["blackberry", "plum", "black pepper", "game", "leather", "earth", "herbs"],
    serving: "Great with grilled lamb, game, barbecue, braised meats, and hearty stews.",
    relevance: 55,
  },
  {
    name: "Viognier",
    color: "white",
    origin_country: "France",
    main_regions: ["Northern Rhône", "Condrieu", "Languedoc", "California", "Australia", "South Africa"],
    synonyms: ["Viognier Blanc"],
    is_blending_grape: true,
    notes: ["apricot", "peach", "pear", "honeysuckle", "violet", "orange blossom"],
    serving: "Great with roast chicken, creamy dishes, grilled pork, aromatic curries, and soft cheeses.",
    relevance: 55,
  },
  {
    name: "Gewürztraminer",
    color: "white",
    origin_country: "Italy",
    main_regions: ["Alsace", "Germany", "Alto Adige", "New Zealand", "Australia", "Washington State"],
    synonyms: ["Traminer Aromatico", "Roter Traminer"],
    is_blending_grape: false,
    notes: ["lychee", "rose", "ginger", "tropical fruit", "spice", "grapefruit"],
    serving: "Great with spicy Asian food, Thai curry, aromatic dishes, smoked meats, and strong cheeses.",
    relevance: 55,
  },
  {
    name: "Glera",
    color: "white",
    origin_country: "Italy",
    main_regions: ["Veneto", "Friuli-Venezia Giulia", "Prosecco", "Conegliano", "Valdobbiadene"],
    synonyms: ["Prosecco", "Prosecco Tondo"],
    is_blending_grape: false,
    notes: ["green apple", "pear", "white peach", "citrus", "white flowers", "almond"],
    serving: "Great as an aperitif and with seafood, sushi, fried foods, salads, and light antipasti.",
    relevance: 55,
  },
  {
    name: "Monastrell",
    color: "red",
    origin_country: "Spain",
    main_regions: ["Jumilla", "Yecla", "Alicante", "Valencia", "Murcia"],
    synonyms: ["Mourvèdre", "Mataro", "Monastrell"],
    is_blending_grape: true,
    notes: ["blackberry", "plum", "black cherry", "pepper", "leather", "herbs"],
    serving: "Great with grilled lamb, barbecue, game, stews, and strong cheeses.",
    relevance: 55,
  },
  {
    name: "Sémillon",
    color: "white",
    origin_country: "France",
    main_regions: ["Bordeaux", "Sauternes", "Hunter Valley", "Margaret River", "Washington State"],
    synonyms: ["Semillon Blanc", "Hunter River Riesling"],
    is_blending_grape: true,
    notes: ["lemon", "apple", "fig", "lanolin", "honey", "toast", "wax"],
    serving: "Great with seafood, roast chicken, creamy dishes, blue cheese, and foie gras.",
    relevance: 52,
  },
  {
    name: "Nero d'Avola",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Sicily", "Noto", "Pachino", "Agrigento"],
    synonyms: ["Calabrese", "Calabrese d'Avola"],
    is_blending_grape: true,
    notes: ["black cherry", "plum", "blackberry", "chocolate", "herbs", "spice"],
    serving: "Great with grilled meats, barbecue, pasta, pizza, lamb, and hearty stews.",
    relevance: 50,
  },
  {
    name: "Vermentino",
    color: "white",
    origin_country: "Italy",
    main_regions: ["Sardinia", "Liguria", "Tuscany", "Corsica", "Languedoc"],
    synonyms: ["Rolle", "Pigato", "Favorita"],
    is_blending_grape: true,
    notes: ["lemon", "lime", "green apple", "pear", "herbs", "saline", "almond"],
    serving: "Great with seafood, grilled fish, shellfish, salads, and Mediterranean vegetables.",
    relevance: 48,
  },
  {
    name: "Montepulciano",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Abruzzo", "Marche", "Molise", "Puglia"],
    synonyms: ["Montepulciano d'Abruzzo"],
    is_blending_grape: true,
    notes: ["black cherry", "plum", "blackberry", "violet", "licorice", "spice"],
    serving: "Great with pizza, pasta, grilled meats, sausages, and tomato-based dishes.",
    relevance: 48,
  },
  {
    name: "Torrontés",
    color: "white",
    origin_country: "Argentina",
    main_regions: ["Argentina", "Salta", "Mendoza", "La Rioja"],
    synonyms: ["Torrontés Riojano", "Torrontés Mendocino"],
    is_blending_grape: false,
    notes: ["peach", "apricot", "rose", "orange blossom", "grape", "citrus"],
    serving: "Great with empanadas, ceviche, spicy food, seafood, salads, and Asian cuisine.",
    relevance: 45,
  },
  {
    name: "Aglianico",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Basilicata", "Campania", "Taurasi", "Vulture", "Puglia"],
    synonyms: ["Aglianico del Vulture", "Uva Nera"],
    is_blending_grape: true,
    notes: ["black cherry", "plum", "violet", "leather", "tobacco", "chocolate", "spice"],
    serving: "Great with braised beef, lamb, game, rich pasta, and aged cheeses.",
    relevance: 45,
  },
  {
    name: "Touriga Nacional",
    color: "red",
    origin_country: "Portugal",
    main_regions: ["Douro", "Dão", "Alentejo", "Tejo"],
    synonyms: ["Touriga"],
    is_blending_grape: true,
    notes: ["blackberry", "blackcurrant", "violet", "plum", "licorice", "herbs"],
    serving: "Great with roast lamb, beef, game, rich stews, and aged cheeses.",
    relevance: 45,
  },
  {
    name: "Touriga Nacional",
    color: "red",
    origin_country: "Portugal",
    main_regions: ["Douro", "Dão", "Alentejo"],
    synonyms: ["Touriga"],
    is_blending_grape: true,
    notes: ["blackberry", "blackcurrant", "violet", "plum", "licorice", "herbs"],
    serving: "Great with roast lamb, beef, game, rich stews, and aged cheeses.",
    relevance: 45,
  },
  {
    name: "Assyrtiko",
    color: "white",
    origin_country: "Greece",
    main_regions: ["Santorini", "Cyclades", "Macedonia", "Crete"],
    synonyms: ["Assyrtico", "Asyrtiko"],
    is_blending_grape: true,
    notes: ["lemon", "lime", "green apple", "saline", "minerals", "herbs"],
    serving: "Great with oysters, grilled fish, octopus, seafood, Greek salads, and feta.",
    relevance: 42,
  },
  {
    name: "Verdejo",
    color: "white",
    origin_country: "Spain",
    main_regions: ["Rueda", "Castilla y León", "Toro"],
    synonyms: ["Verdeja", "Verdejo Blanco"],
    is_blending_grape: true,
    notes: ["lime", "grapefruit", "green apple", "pear", "herbs", "grass"],
    serving: "Great with seafood, shellfish, salads, tapas, grilled fish, and goat cheese.",
    relevance: 42,
  },
  {
    name: "Corvina",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Valpolicella", "Amarone", "Bardolino", "Veneto"],
    synonyms: ["Corvina Veronese", "Cassabria"],
    is_blending_grape: true,
    notes: ["cherry", "red plum", "violet", "almond", "herbs", "spice"],
    serving: "Great with pasta, risotto, roast pork, duck, and aged cheeses.",
    relevance: 40,
  },
  {
    name: "Marsanne",
    color: "white",
    origin_country: "France",
    main_regions: ["Northern Rhône", "Hermitage", "Crozes-Hermitage", "Australia", "California"],
    synonyms: ["Marsanne Blanche", "Ermitage"],
    is_blending_grape: true,
    notes: ["pear", "peach", "honeysuckle", "almond", "honey", "wax"],
    serving: "Great with roast poultry, creamy seafood, lobster, pork, and rich cheeses.",
    relevance: 40,
  },
  {
    name: "Roussanne",
    color: "white",
    origin_country: "France",
    main_regions: ["Northern Rhône", "Hermitage", "Crozes-Hermitage", "Languedoc", "California", "Australia"],
    synonyms: ["Bergeron"],
    is_blending_grape: true,
    notes: ["pear", "apricot", "honeysuckle", "honey", "tea", "almond"],
    serving: "Great with roast chicken, lobster, creamy seafood, mushrooms, and rich cheeses.",
    relevance: 40,
  },
  {
    name: "Fiano",
    color: "white",
    origin_country: "Italy",
    main_regions: ["Campania", "Fiano di Avellino", "Puglia", "Sicily", "Australia"],
    synonyms: ["Fiano di Avellino", "Apianum"],
    is_blending_grape: false,
    notes: ["pear", "apple", "hazelnut", "honey", "citrus", "herbs", "minerals"],
    serving: "Great with seafood, shellfish, grilled fish, pasta, poultry, and creamy dishes.",
    relevance: 40,
  },
  {
    name: "Carménère",
    color: "red",
    origin_country: "France",
    main_regions: ["Chile", "Colchagua Valley", "Maipo Valley", "Bordeaux"],
    synonyms: ["Grande Vidure", "Carmenère"],
    is_blending_grape: true,
    notes: ["blackberry", "plum", "bell pepper", "herbs", "violet", "dark chocolate"],
    serving: "Great with grilled beef, lamb, barbecue, roasted vegetables, and spicy dishes.",
    relevance: 40,
  },
  {
    name: "Verdicchio",
    color: "white",
    origin_country: "Italy",
    main_regions: ["Marche", "Castelli di Jesi", "Matelica"],
    synonyms: ["Trebbiano di Lugana", "Verdicchio Bianco"],
    is_blending_grape: false,
    notes: ["lemon", "green apple", "pear", "almond", "fennel", "minerals"],
    serving: "Great with shellfish, grilled fish, seafood pasta, sushi, and antipasti.",
    relevance: 38,
  },
  {
    name: "Petit Verdot",
    color: "red",
    origin_country: "France",
    main_regions: ["Bordeaux", "Médoc", "Napa Valley", "Australia", "Spain"],
    synonyms: ["Petit Verdau", "Verdot"],
    is_blending_grape: true,
    notes: ["blackberry", "blueberry", "violet", "plum", "graphite", "spice"],
    serving: "Great with steak, lamb, game, barbecue, and strong aged cheeses.",
    relevance: 38,
  },
  {
    name: "Dolcetto",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Piedmont", "Alba", "Dogliani", "Monferrato"],
    synonyms: ["Ormeasco", "Nibiò"],
    is_blending_grape: false,
    notes: ["black cherry", "plum", "violet", "licorice", "almond", "herbs"],
    serving: "Great with pasta, pizza, antipasti, mushrooms, and roasted poultry.",
    relevance: 35,
  },
  {
    name: "Rondinella",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Valpolicella", "Bardolino", "Veneto"],
    synonyms: ["Rondinella Veronese"],
    is_blending_grape: true,
    notes: ["cherry", "red berries", "violet", "herbs", "almond", "spice"],
    serving: "Great with pasta, risotto, roasted meats, mushrooms, and hard cheeses.",
    relevance: 35,
  },
  {
    name: "Garganega",
    color: "white",
    origin_country: "Italy",
    main_regions: ["Soave", "Gambellara", "Veneto", "Sicily"],
    synonyms: ["Grecanico Dorato"],
    is_blending_grape: true,
    notes: ["lemon", "pear", "peach", "almond", "white flowers", "mineral"],
    serving: "Great with seafood, risotto, pasta, grilled vegetables, and fresh cheeses.",
    relevance: 35,
  },
  {
    name: "Negroamaro",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Puglia", "Salento", "Brindisi", "Lecce"],
    synonyms: ["Negro Amaro", "Niuru Maru"],
    is_blending_grape: true,
    notes: ["blackberry", "black cherry", "plum", "licorice", "earth", "herbs"],
    serving: "Great with grilled lamb, barbecue, pasta, pizza, and roasted vegetables.",
    relevance: 35,
  },
  {
    name: "Mencía",
    color: "red",
    origin_country: "Spain",
    main_regions: ["Bierzo", "Ribeira Sacra", "Valdeorras", "Galicia"],
    synonyms: ["Jaen", "Mencía Gallega"],
    is_blending_grape: false,
    notes: ["raspberry", "cherry", "blackberry", "violet", "herbs", "earth", "pepper"],
    serving: "Great with roast pork, lamb, mushrooms, grilled vegetables, and charcuterie.",
    relevance: 35,
  },
  {
    name: "Tinta Roriz",
    color: "red",
    origin_country: "Portugal",
    main_regions: ["Douro", "Alentejo", "Dão"],
    synonyms: ["Tempranillo", "Aragonez", "Tinta de Madrid"],
    is_blending_grape: true,
    notes: ["plum", "cherry", "blackberry", "leather", "tobacco", "spice"],
    serving: "Great with lamb, pork, grilled meats, chorizo, and hearty stews.",
    relevance: 35,
  },
  {
    name: "Rondinella",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Veneto", "Valpolicella", "Bardolino"],
    synonyms: ["Rondinella Veronese"],
    is_blending_grape: true,
    notes: ["cherry", "red berries", "violet", "almond", "herbs", "spice"],
    serving: "Great with pasta, risotto, roasted meats, mushrooms, and hard cheeses.",
    relevance: 35,
  },
  {
    name: "Mencía",
    color: "red",
    origin_country: "Spain",
    main_regions: ["Bierzo", "Ribeira Sacra", "Valdeorras"],
    synonyms: ["Jaén", "Mencía Gallega"],
    is_blending_grape: false,
    notes: ["raspberry", "cherry", "blackberry", "violet", "herbs", "earth"],
    serving: "Great with roast pork, lamb, mushrooms, grilled vegetables, and charcuterie.",
    relevance: 35,
  },
  {
    name: "Falanghina",
    color: "white",
    origin_country: "Italy",
    main_regions: ["Campania", "Benevento", "Sannio", "Irpinia"],
    synonyms: ["Falanghina Beneventana"],
    is_blending_grape: false,
    notes: ["lemon", "apple", "pear", "peach", "white flowers", "almond"],
    serving: "Great with seafood, shellfish, salads, grilled fish, and fresh cheeses.",
    relevance: 33,
  },
  {
    name: "Greco",
    color: "white",
    origin_country: "Italy",
    main_regions: ["Campania", "Greco di Tufo", "Calabria", "Puglia"],
    synonyms: ["Greco Bianco", "Greco di Tufo"],
    is_blending_grape: false,
    notes: ["lemon", "pear", "peach", "almond", "herbs", "minerals"],
    serving: "Great with shellfish, grilled fish, seafood pasta, poultry, and Mediterranean food.",
    relevance: 32,
  },
  {
    name: "Tannat",
    color: "red",
    origin_country: "France",
    main_regions: ["Madiran", "Uruguay", "Canelones", "Rivera", "Argentina"],
    synonyms: ["Harriague", "Moustrou"],
    is_blending_grape: true,
    notes: ["blackberry", "black plum", "violet", "leather", "tobacco", "dark chocolate"],
    serving: "Great with steak, lamb, barbecue, hearty stews, and aged cheeses.",
    relevance: 32,
  },
  {
    name: "Arneis",
    color: "white",
    origin_country: "Italy",
    main_regions: ["Piedmont", "Roero", "Langhe"],
    synonyms: ["Nebbiolo Bianco", "Bianchetto"],
    is_blending_grape: false,
    notes: ["pear", "peach", "almond", "citrus", "white flowers", "herbs"],
    serving: "Great with seafood, salads, poultry, antipasti, and fresh cheeses.",
    relevance: 30,
  },
  {
    name: "Xinomavro",
    color: "red",
    origin_country: "Greece",
    main_regions: ["Naoussa", "Amyndeon", "Macedonia", "Rapsani"],
    synonyms: ["Xynómavro", "Mavro Naoussis"],
    is_blending_grape: true,
    notes: ["red cherry", "raspberry", "tomato", "olive", "violet", "leather", "spice"],
    serving: "Great with lamb, grilled meats, tomato dishes, mushrooms, and aged cheeses.",
    relevance: 30,
  },
  {
    name: "Bobal",
    color: "red",
    origin_country: "Spain",
    main_regions: ["Utiel-Requena", "Manchuela", "Valencia"],
    synonyms: ["Bobal Noir", "Bobal de Cuenca"],
    is_blending_grape: true,
    notes: ["blackberry", "blueberry", "plum", "violet", "herbs", "spice"],
    serving: "Great with grilled meats, lamb, stews, sausages, and roasted vegetables.",
    relevance: 30,
  },
  {
    name: "Godello",
    color: "white",
    origin_country: "Spain",
    main_regions: ["Valdeorras", "Bierzo", "Monterrei", "Galicia"],
    synonyms: ["Gouveio", "Verdelho"],
    is_blending_grape: false,
    notes: ["apple", "pear", "peach", "lemon", "almond", "minerals"],
    serving: "Great with seafood, grilled fish, shellfish, roast poultry, and creamy dishes.",
    relevance: 30,
  },
  {
    name: "Palomino",
    color: "white",
    origin_country: "Spain",
    main_regions: ["Jerez", "Sanlúcar de Barrameda", "El Puerto de Santa María", "Montilla-Moriles"],
    synonyms: ["Palomino Fino", "Listán", "Jerez"],
    is_blending_grape: true,
    notes: ["almond", "apple", "citrus", "dough", "salt", "minerals"],
    serving: "Great with tapas, almonds, olives, seafood, fried fish, and cured meats.",
    relevance: 30,
  },
  {
    name: "Touriga Franca",
    color: "red",
    origin_country: "Portugal",
    main_regions: ["Douro", "Dão", "Alentejo"],
    synonyms: ["Touriga Francesa", "Touriga Franceza"],
    is_blending_grape: true,
    notes: ["blackberry", "raspberry", "violet", "rose", "herbs", "spice"],
    serving: "Great with lamb, game, grilled meats, rich stews, and Portuguese cheeses.",
    relevance: 30,
  },
  {
    name: "Pinotage",
    color: "red",
    origin_country: "South Africa",
    main_regions: ["Stellenbosch", "Paarl", "Swartland", "Western Cape"],
    synonyms: ["Pinotage"],
    is_blending_grape: true,
    notes: ["blackberry", "plum", "banana", "smoke", "coffee", "chocolate", "spice"],
    serving: "Great with barbecue, grilled meats, game, spicy sausages, and smoked foods.",
    relevance: 30,
  },
  {
    name: "Pecorino",
    color: "white",
    origin_country: "Italy",
    main_regions: ["Abruzzo", "Marche", "Offida", "Teramo"],
    synonyms: ["Pecorino Abruzzo", "Pecorino Marche"],
    is_blending_grape: false,
    notes: ["lemon", "pear", "apple", "white flowers", "herbs", "minerals"],
    serving: "Great with seafood, grilled fish, pasta, salads, and fresh cheeses.",
    relevance: 28,
  },
  {
    name: "Friulano",
    color: "white",
    origin_country: "Italy",
    main_regions: ["Friuli-Venezia Giulia", "Collio", "Colli Orientali"],
    synonyms: ["Sauvignon Vert", "Sauvignonasse", "Tocai Friulano"],
    is_blending_grape: false,
    notes: ["pear", "green apple", "almond", "herbs", "citrus", "white flowers"],
    serving: "Great with prosciutto, seafood, salads, pasta, and fresh cheeses.",
    relevance: 28,
  },
  {
    name: "Agiorgitiko",
    color: "red",
    origin_country: "Greece",
    main_regions: ["Nemea", "Peloponnese", "Corinthia", "Attica"],
    synonyms: ["St. George", "Mavro Nemeas"],
    is_blending_grape: true,
    notes: ["cherry", "raspberry", "plum", "violet", "spice", "herbs"],
    serving: "Great with grilled lamb, pork, roasted vegetables, pasta, and Mediterranean dishes.",
    relevance: 28,
  },
  {
    name: "Pedro Ximénez",
    color: "white",
    origin_country: "Spain",
    main_regions: ["Montilla-Moriles", "Jerez", "Málaga"],
    synonyms: ["PX", "Pedro Jiménez"],
    is_blending_grape: false,
    notes: ["raisin", "fig", "date", "molasses", "caramel", "coffee", "chocolate"],
    serving: "Great with blue cheese, vanilla ice cream, chocolate desserts, dried fruit, and pastries.",
    relevance: 28,
  },
  {
    name: "Carignan",
    color: "red",
    origin_country: "Spain",
    main_regions: ["Languedoc", "Roussillon", "Priorat", "Rioja", "California"],
    synonyms: ["Cariñena", "Carignane", "Mazuelo", "Samsó"],
    is_blending_grape: true,
    notes: ["blackberry", "plum", "cherry", "herbs", "pepper", "earth"],
    serving: "Great with lamb, sausages, cassoulet, grilled meats, and hearty stews.",
    relevance: 28,
  },
  {
    name: "Furmint",
    color: "white",
    origin_country: "Hungary",
    main_regions: ["Tokaj", "Somló", "Slovakia"],
    synonyms: ["Mosler", "Šipon"],
    is_blending_grape: true,
    notes: ["green apple", "pear", "citrus", "honey", "minerals", "spice"],
    serving: "Great with seafood, poultry, spicy dishes, blue cheese, and sweet desserts.",
    relevance: 28,
  },
  {
    name: "Ribolla Gialla",
    color: "white",
    origin_country: "Italy",
    main_regions: ["Friuli-Venezia Giulia", "Collio", "Slovenia", "Gorizia"],
    synonyms: ["Rebula", "Ribolla"],
    is_blending_grape: true,
    notes: ["lemon", "green apple", "pear", "white flowers", "minerals", "herbs"],
    serving: "Great with seafood, shellfish, salads, antipasti, and light pasta.",
    relevance: 25,
  },
  {
    name: "Garnacha Blanca",
    color: "white",
    origin_country: "Spain",
    main_regions: ["Catalonia", "Terra Alta", "Priorat", "Rioja", "Rhône Valley"],
    synonyms: ["Grenache Blanc", "Garnatxa Blanca"],
    is_blending_grape: true,
    notes: ["pear", "green apple", "citrus", "fennel", "white flowers", "herbs"],
    serving: "Great with grilled fish, shellfish, roast poultry, creamy dishes, and Mediterranean food.",
    relevance: 25,
  },
  {
    name: "Cinsault",
    color: "red",
    origin_country: "France",
    main_regions: ["Languedoc", "Rhône Valley", "Provence", "South Africa", "Lebanon"],
    synonyms: ["Cinsaut", "Hermitage"],
    is_blending_grape: true,
    notes: ["strawberry", "raspberry", "cherry", "violet", "herbs", "pepper"],
    serving: "Great with roast chicken, charcuterie, grilled vegetables, pizza, and Mediterranean food.",
    relevance: 25,
  },
  {
    name: "Aligoté",
    color: "white",
    origin_country: "France",
    main_regions: ["Burgundy", "Bouzeron", "Mâconnais", "Eastern Europe"],
    synonyms: ["Aligotay", "Plant de Trois"],
    is_blending_grape: false,
    notes: ["lemon", "green apple", "pear", "white flowers", "minerals", "herbs"],
    serving: "Great with oysters, seafood, goat cheese, salads, and Burgundy-style dishes.",
    relevance: 25,
  },
  {
    name: "Blaufränkisch",
    color: "red",
    origin_country: "Austria",
    main_regions: ["Burgenland", "Mittelburgenland", "Hungary", "Germany", "Slovakia"],
    synonyms: ["Lemberger", "Kékfrankos", "Frankovka"],
    is_blending_grape: true,
    notes: ["black cherry", "blackberry", "blueberry", "pepper", "violet", "spice"],
    serving: "Great with grilled meats, duck, game, sausages, and roasted vegetables.",
    relevance: 25,
  },
  {
    name: "Macabeo",
    color: "white",
    origin_country: "Spain",
    main_regions: ["Rioja", "Catalonia", "Penedès", "Rueda", "Languedoc"],
    synonyms: ["Viura", "Macabeu", "Riojana"],
    is_blending_grape: true,
    notes: ["apple", "pear", "citrus", "almond", "white flowers", "herbs"],
    serving: "Great with seafood, tapas, salads, poultry, and soft cheeses.",
    relevance: 25,
  },
  {
    name: "Moschofilero",
    color: "white",
    origin_country: "Greece",
    main_regions: ["Mantinia", "Peloponnese", "Arcadia"],
    synonyms: ["Moschophilero"],
    is_blending_grape: false,
    notes: ["rose", "lychee", "citrus", "peach", "white flowers", "herbs"],
    serving: "Great with seafood, salads, sushi, mezze, and spicy Asian dishes.",
    relevance: 22,
  },
  {
    name: "Baga",
    color: "red",
    origin_country: "Portugal",
    main_regions: ["Bairrada", "Beiras", "Dão"],
    synonyms: ["Baga de Louro", "Poeirinho"],
    is_blending_grape: true,
    notes: ["red cherry", "raspberry", "plum", "earth", "herbs", "tobacco"],
    serving: "Great with roast pork, suckling pig, grilled meats, mushrooms, and aged cheeses.",
    relevance: 22,
  },
  {
    name: "Bonarda",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Argentina", "Mendoza", "San Juan", "Piedmont"],
    synonyms: ["Charbono", "Douce Noire", "Corbeau"],
    is_blending_grape: true,
    notes: ["blackberry", "plum", "blueberry", "violet", "spice", "chocolate"],
    serving: "Great with barbecue, steak, burgers, sausages, and grilled vegetables.",
    relevance: 22,
  },
  {
    name: "Colombard",
    color: "white",
    origin_country: "France",
    main_regions: ["Gascony", "Cognac", "Armagnac", "California", "South Africa"],
    synonyms: ["Colombar", "French Colombard"],
    is_blending_grape: true,
    notes: ["grapefruit", "lemon", "green apple", "pear", "passionfruit", "herbs"],
    serving: "Great with seafood, salads, shellfish, light poultry, and fresh cheeses.",
    relevance: 22,
  },
  {
    name: "Zweigelt",
    color: "red",
    origin_country: "Austria",
    main_regions: ["Burgenland", "Lower Austria", "Carnuntum"],
    synonyms: ["Rotburger"],
    is_blending_grape: true,
    notes: ["cherry", "raspberry", "blackberry", "violet", "pepper", "spice"],
    serving: "Great with roast poultry, pork, sausages, mushrooms, and grilled vegetables.",
    relevance: 22,
  },
  {
    name: "Verdelho",
    color: "white",
    origin_country: "Portugal",
    main_regions: ["Madeira", "Australia", "Hunter Valley", "South Australia", "Portugal"],
    synonyms: ["Gouveio", "Verdelho Branco"],
    is_blending_grape: true,
    notes: ["lime", "passionfruit", "pear", "citrus", "herbs", "tropical fruit"],
    serving: "Great with seafood, spicy Asian food, grilled fish, salads, and light curries.",
    relevance: 22,
  },
  {
    name: "Castelão",
    color: "red",
    origin_country: "Portugal",
    main_regions: ["Setúbal", "Palmela", "Tejo", "Algarve"],
    synonyms: ["Periquita", "João de Santarém"],
    is_blending_grape: true,
    notes: ["red berries", "plum", "blackberry", "violet", "leather", "herbs"],
    serving: "Great with grilled meats, roast pork, poultry, stews, and Portuguese dishes.",
    relevance: 20,
  },
  {
    name: "Loureiro",
    color: "white",
    origin_country: "Portugal",
    main_regions: ["Vinho Verde", "Minho", "Lima Valley"],
    synonyms: ["Loureiro Branco"],
    is_blending_grape: true,
    notes: ["lime", "lemon", "bay leaf", "white flowers", "green apple", "herbs"],
    serving: "Great with oysters, shellfish, grilled fish, salads, and fresh cheeses.",
    relevance: 20,
  },
  {
    name: "Marselan",
    color: "red",
    origin_country: "France",
    main_regions: ["Languedoc", "Rhône Valley", "China", "California"],
    synonyms: ["Marselan Noir"],
    is_blending_grape: true,
    notes: ["blackberry", "blueberry", "plum", "violet", "pepper", "herbs"],
    serving: "Great with grilled meats, lamb, barbecue, spicy food, and aged cheeses.",
    relevance: 20,
  },
  {
    name: "Rkatsiteli",
    color: "white",
    origin_country: "Georgia",
    main_regions: ["Kakheti", "Kartli", "Georgia", "Ukraine", "Moldova"],
    synonyms: ["Rkatsiteli Mgvane", "Kukura"],
    is_blending_grape: true,
    notes: ["green apple", "quince", "citrus", "pear", "herbs", "minerals"],
    serving: "Great with grilled fish, poultry, vegetables, salads, and Georgian cuisine.",
    relevance: 20,
  },
  {
    name: "Sagrantino",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Umbria", "Montefalco", "Montefalco Sagrantino"],
    synonyms: ["Sagrantino di Montefalco"],
    is_blending_grape: false,
    notes: ["blackberry", "black plum", "violet", "tobacco", "leather", "spice"],
    serving: "Great with grilled beef, lamb, game, truffles, rich stews, and aged cheeses.",
    relevance: 20,
  },
  {
    name: "Fernão Pires",
    color: "white",
    origin_country: "Portugal",
    main_regions: ["Tejo", "Bairrada", "Setúbal", "Lisboa"],
    synonyms: ["Maria Gomes", "Fernam Pires"],
    is_blending_grape: true,
    notes: ["orange blossom", "citrus", "lychee", "lime", "herbs", "spice"],
    serving: "Great with seafood, salads, grilled fish, Asian food, and fresh cheeses.",
    relevance: 18,
  },
  {
    name: "Petit Manseng",
    color: "white",
    origin_country: "France",
    main_regions: ["Jurançon", "Southwest France", "Australia", "Uruguay"],
    synonyms: ["Mansengou", "Petit Mansenc"],
    is_blending_grape: true,
    notes: ["pineapple", "apricot", "passionfruit", "honey", "citrus", "spice"],
    serving: "Great with foie gras, blue cheese, fruit desserts, spicy food, and pastries.",
    relevance: 18,
  },
  {
    name: "Saperavi",
    color: "red",
    origin_country: "Georgia",
    main_regions: ["Kakheti", "Kartli", "Georgia", "Moldova", "Ukraine"],
    synonyms: ["Saperavi Budeshuri"],
    is_blending_grape: false,
    notes: ["blackberry", "black plum", "cherry", "violet", "spice", "earth"],
    serving: "Great with grilled meats, stews, lamb, game, barbecue, and hearty Georgian cuisine.",
    relevance: 18,
  },
  {
    name: "Graciano",
    color: "red",
    origin_country: "Spain",
    main_regions: ["Rioja", "Navarra", "Priorat", "La Mancha"],
    synonyms: ["Morrastel", "Tinta Miúda", "Xeres"],
    is_blending_grape: true,
    notes: ["blackberry", "blueberry", "violet", "black pepper", "licorice", "herbs"],
    serving: "Great with lamb, grilled beef, game, spicy sausages, and aged cheeses.",
    relevance: 18,
  },
  {
    name: "País",
    color: "red",
    origin_country: "Spain",
    main_regions: ["Chile", "Maule", "Itata", "Biobío", "Argentina"],
    synonyms: ["Listán Prieto", "Mission", "Criolla Chica"],
    is_blending_grape: true,
    notes: ["strawberry", "cherry", "raspberry", "herbs", "pepper", "earth"],
    serving: "Great with empanadas, grilled vegetables, poultry, charcuterie, and light barbecue.",
    relevance: 15,
  },
  {
    name: "Clairette",
    color: "white",
    origin_country: "France",
    main_regions: ["Rhône Valley", "Languedoc", "Provence", "Beaucaire"],
    synonyms: ["Clairette Blanche", "Clairette"],
    is_blending_grape: true,
    notes: ["apple", "pear", "citrus", "white flowers", "fennel", "herbs"],
    serving: "Great with seafood, shellfish, salads, grilled fish, and Mediterranean dishes.",
    relevance: 15,
  },
  {
    name: "Mazuelo",
    color: "red",
    origin_country: "Spain",
    main_regions: ["Rioja", "Catalonia", "Priorat", "Aragon"],
    synonyms: ["Cariñena", "Carignan", "Samsó"],
    is_blending_grape: true,
    notes: ["blackberry", "plum", "cherry", "herbs", "pepper", "earth"],
    serving: "Great with lamb, grilled meats, stews, sausages, and aged cheeses.",
    relevance: 15,
  },
  {
    name: "Tinta Barroca",
    color: "red",
    origin_country: "Portugal",
    main_regions: ["Douro", "Dão", "Alentejo"],
    synonyms: ["Tinta Barocca", "Tinta Gorda"],
    is_blending_grape: true,
    notes: ["blackberry", "plum", "black cherry", "violet", "spice", "chocolate"],
    serving: "Great with roast lamb, beef, game, stews, and aged cheeses.",
    relevance: 15,
  },
  {
    name: "Nero di Troia",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Puglia", "Daunia", "Castel del Monte"],
    synonyms: ["Uva di Troia", "Sumarello"],
    is_blending_grape: true,
    notes: ["black cherry", "plum", "violet", "blackberry", "spice", "herbs"],
    serving: "Great with lamb, grilled meats, pasta, roasted vegetables, and aged cheeses.",
    relevance: 15,
  },
  {
    name: "Savagnin",
    color: "white",
    origin_country: "France",
    main_regions: ["Jura", "Arbois", "L'Étoile", "Côtes du Jura"],
    synonyms: ["Traminer", "Naturé"],
    is_blending_grape: false,
    notes: ["green apple", "walnut", "almond", "curry", "dried fruit", "minerals"],
    serving: "Great with Comté cheese, mushrooms, poultry, creamy dishes, and Asian cuisine.",
    relevance: 12,
  },
  {
    name: "St. Laurent",
    color: "red",
    origin_country: "Austria",
    main_regions: ["Burgenland", "Lower Austria", "Czech Republic"],
    synonyms: ["Sankt Laurent", "Laurenztraube"],
    is_blending_grape: false,
    notes: ["black cherry", "raspberry", "plum", "violet", "spice", "earth"],
    serving: "Great with duck, roast pork, mushrooms, game, and charcuterie.",
    relevance: 12,
  },
  {
    name: "Refosco",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Friuli-Venezia Giulia", "Colli Orientali", "Veneto", "Slovenia"],
    synonyms: ["Refosco dal Peduncolo Rosso", "Refosco Nostrano"],
    is_blending_grape: true,
    notes: ["black cherry", "blackberry", "plum", "violet", "herbs", "spice"],
    serving: "Great with game, grilled meats, pork, mushrooms, and hearty regional dishes.",
    relevance: 12,
  },
  {
    name: "Fetească Neagră",
    color: "red",
    origin_country: "Romania",
    main_regions: ["Romania", "Moldova", "Dealu Mare", "Moldavia"],
    synonyms: ["Black Maiden", "Feteasca Neagra"],
    is_blending_grape: true,
    notes: ["blackberry", "plum", "black cherry", "violet", "spice", "smoke"],
    serving: "Great with grilled meats, lamb, game, stews, and smoked foods.",
    relevance: 12,
  },
  {
    name: "Jacquère",
    color: "white",
    origin_country: "France",
    main_regions: ["Savoie", "Apremont", "Abymes", "Combe de Savoie"],
    synonyms: ["Jacquère Blanche"],
    is_blending_grape: false,
    notes: ["green apple", "lemon", "pear", "white flowers", "herbs", "minerals"],
    serving: "Great with fondue, raclette, seafood, salads, and fresh cheeses.",
    relevance: 10,
  },
  {
    name: "Mondeuse",
    color: "red",
    origin_country: "France",
    main_regions: ["Savoie", "Bugey", "Alps"],
    synonyms: ["Mondeuse Noire", "Mandoleuse"],
    is_blending_grape: false,
    notes: ["blackberry", "black cherry", "violet", "pepper", "herbs", "earth"],
    serving: "Great with game, grilled meats, charcuterie, mushrooms, and alpine cheeses.",
    relevance: 10,
  },
  {
    name: "Trousseau",
    color: "red",
    origin_country: "France",
    main_regions: ["Jura", "Arbois", "Côtes du Jura"],
    synonyms: ["Trousseau Noir", "Merenzao", "Bastardo"],
    is_blending_grape: true,
    notes: ["red cherry", "raspberry", "strawberry", "pepper", "earth", "herbs"],
    serving: "Great with roast poultry, pork, charcuterie, mushrooms, and alpine cheeses.",
    relevance: 10,
  },
  {
    name: "Poulsard",
    color: "red",
    origin_country: "France",
    main_regions: ["Jura", "Arbois", "Côtes du Jura"],
    synonyms: ["Ploussard", "Pelossard"],
    is_blending_grape: false,
    notes: ["strawberry", "raspberry", "cherry", "violet", "earth", "pepper"],
    serving: "Great with charcuterie, roast chicken, mushrooms, pork, and light cheeses.",
    relevance: 10,
  },
  {
    name: "Kadarka",
    color: "red",
    origin_country: "Hungary",
    main_regions: ["Hungary", "Szekszárd", "Villány", "Serbia", "Bulgaria"],
    synonyms: ["Gamza", "Cadarca", "Skadarka"],
    is_blending_grape: true,
    notes: ["raspberry", "strawberry", "cherry", "paprika", "violet", "spice"],
    serving: "Great with grilled meats, paprika dishes, sausages, roast poultry, and charcuterie.",
    relevance: 10,
  },
  {
    name: "Kadarka",
    color: "red",
    origin_country: "Hungary",
    main_regions: ["Hungary", "Szekszárd", "Serbia", "Bulgaria"],
    synonyms: ["Gamza", "Cadarca", "Skadarka"],
    is_blending_grape: true,
    notes: ["raspberry", "strawberry", "cherry", "paprika", "violet", "spice"],
    serving: "Great with grilled meats, paprika dishes, sausages, roast poultry, and charcuterie.",
    relevance: 10,
  },
  {
    name: "Schioppettino",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Friuli-Venezia Giulia", "Colli Orientali", "Prepotto"],
    synonyms: ["Ribolla Nera", "Pokalza"],
    is_blending_grape: false,
    notes: ["blackberry", "black cherry", "violet", "black pepper", "spice", "earth"],
    serving: "Great with game, grilled meats, mushrooms, sausages, and aged cheeses.",
    relevance: 8,
  },
  {
    name: "Pignolo",
    color: "red",
    origin_country: "Italy",
    main_regions: ["Friuli-Venezia Giulia", "Colli Orientali"],
    synonyms: ["Pignul"],
    is_blending_grape: false,
    notes: ["black cherry", "plum", "violet", "leather", "spice", "earth"],
    serving: "Great with braised beef, game, lamb, mushrooms, and aged cheeses.",
    relevance: 6,
  },
]

puts "Seeding grapes..."
grapes_data.each do |grape_data|
  Grape.find_or_create_by!(name: grape_data[:name]) do |g|
    g.assign_attributes(grape_data)
  end
end
puts "Done! Created #{Grape.count} grapes."