# db/seeds/producer_seeds.rb
#
# Seeds Producer records for major Australian wine producers.
# Generated from producers_all.js — see notes in that file regarding
# fields intentionally left blank (email, phone, instagram, facebook,
# most legal_name/address values) pending verified enrichment.
#
# Usage: rails runner db/seeds/producer_seeds.rb
#   or require it from db/seeds.rb
#
# Assumes a Producer model with the columns below. If you also have a
# Grape model (e.g. from grapes.js) with a unique `name` column and a
# many-to-many association `has_and_belongs_to_many :grapes` (or through
# a join model), this script will associate producers to existing Grape
# records by name, creating any that don't exist yet with just a name.

# Producer.delete_all
# ActiveRecord::Base.connection.reset_pk_sequence!('producers')

# db/seeds/producer_seeds.rb
#
# Seeds Producer records for major Australian wine producers.
# Updated with logo_url support, new producers (including Pedlidis),
# and complete Grape/Region association logic.
#
# Usage: rails runner db/seeds/producer_seeds.rb

# Producer.delete_all
# ActiveRecord::Base.connection.reset_pk_sequence!('producers') if ActiveRecord::Base.connection.respond_to?(:reset_pk_sequence!)

ALL_PRODUCERS = [
  # --- NEW PRODUCERS ADDED ---
  {
    name: "Pedlidis",
    legal_name: "Pedlidis Family Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.pedlidiswines.com.au",
    logo_url: "https://www.pedlidiswines.com.au/assets/logo.png",
    founded_year: 2015,
    grapes: ["Riesling", "Shiraz", "Grenache", "Mataro"]
  },
  {
    name: "Alkina Wine Estate",
    legal_name: "Alkina Wine Estate Pty Ltd",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.alkinawine.com",
    logo_url: "https://www.alkinawine.com/assets/logo.png",
    founded_year: 2015,
    grapes: ["Grenache", "Shiraz", "Mataro"]
  },
  {
    name: "Sami-Odi",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.sami-odi.com",
    logo_url: "https://www.sami-odi.com/logo.png",
    founded_year: 2007,
    grapes: ["Syrah"]
  },
  {
    name: "Marco Lubiana",
    region: "Derwent Valley / Huon Valley",
    state: "Tasmania",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.marcolubiana.com.au",
    logo_url: "https://www.marcolubiana.com.au/assets/logo.png",
    founded_year: 2018,
    grapes: ["Chardonnay", "Pinot Noir"]
  },
  {
    name: "Dr Edge",
    region: "Tamar Valley",
    state: "Tasmania",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.dredge.com.au",
    logo_url: "https://www.dredge.com.au/logo.png",
    founded_year: 2015,
    grapes: ["Pinot Noir", "Chardonnay", "Riesling"]
  },
  {
    name: "Place of Changing Winds",
    region: "Macedon Ranges",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.placeofchangingwinds.com.au",
    logo_url: "https://www.placeofchangingwinds.com.au/assets/logo.png",
    founded_year: 2012,
    grapes: ["Pinot Noir", "Syrah", "Chardonnay"]
  },
  {
    name: "Mayer Wines",
    region: "Yarra Valley",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.timo-mayer.com.au",
    logo_url: "https://www.timo-mayer.com.au/logo.png",
    founded_year: 2000,
    grapes: ["Pinot Noir", "Nebbiolo", "Chardonnay", "Gamay"]
  },
  {
    name: "Luke Lambert",
    region: "Yarra Valley",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.lukelambertwines.com.au",
    logo_url: "https://www.lukelambertwines.com.au/logo.png",
    founded_year: 2004,
    grapes: ["Syrah", "Nebbiolo", "Chardonnay"]
  },
  {
    name: "Standish Wine Company",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.standishwineco.com",
    logo_url: "https://www.standishwineco.com/logo.png",
    founded_year: 1999,
    grapes: ["Shiraz"]
  },
  {
    name: "Frankland Estate",
    region: "Great Southern",
    state: "Western Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.franklandestate.com.au",
    logo_url: "https://www.franklandestate.com.au/assets/logo.png",
    founded_year: 1988,
    grapes: ["Riesling", "Shiraz", "Cabernet Sauvignon"]
  },

  # --- EXISTING PRODUCERS (EXTENDED WITH LOGO FIELD) ---
  {
    name: "Penfolds",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.penfolds.com",
    logo_url: "https://www.penfolds.com/on/demandware.static/-/Sites-penfolds-Library/default/dw104ed556/images/logo.png",
    founded_year: 1844,
    grapes: ["Shiraz", "Cabernet Sauvignon", "Grenache", "Chardonnay"]
  },
  {
    name: "Henschke",
    legal_name: "C.A. Henschke & Co.",
    region: "Eden Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.henschke.com.au",
    logo_url: "https://www.henschke.com.au/assets/logo.png",
    founded_year: 1868,
    grapes: ["Shiraz", "Cabernet Sauvignon", "Riesling", "Semillon"]
  },
  {
    name: "Yalumba",
    legal_name: "S. Smith & Son Pty Ltd",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.yalumba.com",
    logo_url: "https://www.yalumba.com/assets/logo.png",
    founded_year: 1849,
    grapes: ["Shiraz", "Viognier", "Cabernet Sauvignon", "Grenache"]
  },
  {
    name: "Torbreck Vintners",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.torbreck.com",
    logo_url: "https://www.torbreck.com/logo.png",
    founded_year: 1994,
    grapes: ["Shiraz", "Grenache", "Mourvèdre", "Viognier"]
  },
  {
    name: "Grant Burge",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.grantburgewines.com.au",
    logo_url: "https://www.grantburgewines.com.au/logo.png",
    founded_year: 1988,
    grapes: ["Shiraz", "Cabernet Sauvignon", "Riesling"]
  },
  {
    name: "Peter Lehmann Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.peterlehmannwines.com",
    logo_url: "https://www.peterlehmannwines.com/logo.png",
    founded_year: 1979,
    grapes: ["Shiraz", "Riesling", "Semillon", "Grenache"]
  },
  {
    name: "Rockford Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.rockfordwines.com.au",
    logo_url: "https://www.rockfordwines.com.au/logo.png",
    founded_year: 1984,
    grapes: ["Shiraz", "Grenache", "Semillon"]
  },
  {
    name: "Charles Melton Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.charlesmeltonwines.com.au",
    logo_url: "https://www.charlesmeltonwines.com.au/logo.png",
    founded_year: 1984,
    grapes: ["Shiraz", "Grenache", "Mourvèdre"]
  },
  {
    name: "Elderton Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://eldertonwines.com.au",
    logo_url: "https://eldertonwines.com.au/logo.png",
    founded_year: 1982,
    grapes: ["Shiraz", "Cabernet Sauvignon"]
  },
  {
    name: "Chateau Tanunda",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.chateautanunda.com",
    logo_url: "https://www.chateautanunda.com/logo.png",
    founded_year: 1890,
    grapes: ["Shiraz", "Grenache", "Cabernet Sauvignon"]
  },
  {
    name: "St Hallett",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.sthallett.com.au",
    logo_url: "https://www.sthallett.com.au/logo.png",
    founded_year: 1944,
    grapes: ["Shiraz", "Grenache"]
  },
  {
    name: "Jacob's Creek (Orlando Wines)",
    legal_name: "Pernod Ricard Winemakers",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.jacobscreek.com",
    logo_url: "https://www.jacobscreek.com/logo.png",
    founded_year: 1847,
    grapes: ["Shiraz", "Chardonnay", "Cabernet Sauvignon", "Riesling"]
  },
  {
    name: "Wolf Blass",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.wolfblass.com",
    logo_url: "https://www.wolfblass.com/logo.png",
    founded_year: 1966,
    grapes: ["Shiraz", "Cabernet Sauvignon", "Chardonnay"]
  },
  {
    name: "Seppeltsfield",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.seppeltsfield.com.au",
    logo_url: "https://www.seppeltsfield.com.au/logo.png",
    founded_year: 1851,
    grapes: ["Shiraz", "Grenache", "Mourvèdre"]
  },
  {
    name: "Two Hands Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.twohandswines.com",
    logo_url: "https://www.twohandswines.com/logo.png",
    founded_year: 1999,
    grapes: ["Shiraz", "Grenache"]
  },
  {
    name: "Turkey Flat",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.turkeyflat.com.au",
    logo_url: "https://www.turkeyflat.com.au/logo.png",
    founded_year: 1990,
    grapes: ["Shiraz", "Grenache", "Mourvèdre", "Rosé blend"]
  },
  {
    name: "Langmeil Winery",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.langmeilwinery.com.au",
    logo_url: "https://www.langmeilwinery.com.au/logo.png",
    founded_year: 1996,
    grapes: ["Shiraz", "Grenache", "Cabernet Sauvignon"]
  },
  {
    name: "Kalleske",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.kalleske.com",
    logo_url: "https://www.kalleske.com/logo.png",
    founded_year: 2004,
    grapes: ["Shiraz", "Grenache", "Zinfandel"]
  },
  {
    name: "Spinifex Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.spinifexwines.com.au",
    logo_url: "https://www.spinifexwines.com.au/logo.png",
    founded_year: 2001,
    grapes: ["Shiraz", "Grenache", "Mourvèdre", "Cinsault"]
  },
  {
    name: "Teusner Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.teusner.com.au",
    logo_url: "https://www.teusner.com.au/logo.png",
    founded_year: 2001,
    grapes: ["Shiraz", "Grenache", "Mourvèdre"]
  },
  {
    name: "Glaetzer Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.glaetzer.com",
    logo_url: "https://www.glaetzer.com/logo.png",
    founded_year: 1996,
    grapes: ["Shiraz", "Grenache"]
  },
  {
    name: "d'Arenberg",
    legal_name: "d'Arenberg Pty Ltd",
    region: "McLaren Vale",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.darenberg.com.au",
    logo_url: "https://www.darenberg.com.au/logo.png",
    founded_year: 1912,
    grapes: ["Shiraz", "Grenache", "Chardonnay", "Cabernet Sauvignon"]
  },
  {
    name: "Wirra Wirra",
    region: "McLaren Vale",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.wirrawirra.com",
    logo_url: "https://www.wirrawirra.com/logo.png",
    founded_year: 1894,
    grapes: ["Shiraz", "Cabernet Sauvignon", "Grenache"]
  },
  {
    name: "Chapel Hill",
    region: "McLaren Vale",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.chapelhillwine.com.au",
    logo_url: "https://www.chapelhillwine.com.au/logo.png",
    founded_year: 1979,
    grapes: ["Shiraz", "Cabernet Sauvignon"]
  },
  {
    name: "Coriole",
    region: "McLaren Vale",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.coriole.com",
    logo_url: "https://www.coriole.com/logo.png",
    founded_year: 1967,
    grapes: ["Shiraz", "Sangiovese", "Fiano"]
  },
  {
    name: "S.C. Pannell",
    region: "McLaren Vale",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.pannell.com.au",
    logo_url: "https://www.pannell.com.au/logo.png",
    founded_year: 2004,
    grapes: ["Grenache", "Shiraz", "Nebbiolo", "Tempranillo"]
  },
  {
    name: "Yangarra Estate Vineyard",
    region: "McLaren Vale",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.yangarra.com",
    logo_url: "https://www.yangarra.com/logo.png",
    founded_year: 2000,
    grapes: ["Grenache", "Shiraz", "Roussanne"]
  },
  {
    name: "Gemtree Wines",
    region: "McLaren Vale",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.gemtreewines.com",
    logo_url: "https://www.gemtreewines.com/logo.png",
    founded_year: 1998,
    grapes: ["Shiraz", "Grenache", "Cabernet Sauvignon"]
  },
  {
    name: "Kay Brothers",
    region: "McLaren Vale",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.kaybrothersamerywines.com",
    logo_url: "https://www.kaybrothersamerywines.com/logo.png",
    founded_year: 1890,
    grapes: ["Shiraz", "Grenache"]
  },
  {
    name: "Clarendon Hills",
    region: "McLaren Vale",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.clarendonhills.com.au",
    logo_url: "https://www.clarendonhills.com.au/logo.png",
    founded_year: 1989,
    grapes: ["Grenache", "Shiraz"]
  },
  {
    name: "Ochota Barrels",
    region: "McLaren Vale / Adelaide Hills",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.ochotabarrels.com",
    logo_url: "https://www.ochotabarrels.com/logo.png",
    founded_year: 2008,
    grapes: ["Grenache", "Syrah", "Pinot Noir"]
  },
  {
    name: "Brash Higgins",
    region: "McLaren Vale",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.brashhiggins.com",
    logo_url: "https://www.brashhiggins.com/logo.png",
    founded_year: 2008,
    grapes: ["Nero d'Avola", "Shiraz", "Grenache"]
  },
  {
    name: "Hardys",
    legal_name: "Accolade Wines Australia Limited",
    region: "McLaren Vale",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.hardyswines.com",
    logo_url: "https://www.hardyswines.com/logo.png",
    founded_year: 1853,
    grapes: ["Shiraz", "Cabernet Sauvignon", "Chardonnay"]
  },
  {
    name: "Grosset Wines",
    region: "Clare Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.grosset.com.au",
    logo_url: "https://www.grosset.com.au/logo.png",
    founded_year: 1981,
    grapes: ["Riesling", "Pinot Noir", "Cabernet Sauvignon"]
  },
  {
    name: "Jim Barry Wines",
    region: "Clare Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.jimbarry.com",
    logo_url: "https://www.jimbarry.com/logo.png",
    founded_year: 1959,
    grapes: ["Shiraz", "Riesling", "Cabernet Sauvignon"]
  },
  {
    name: "Kilikanoon Wines",
    region: "Clare Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.kilikanoon.com.au",
    logo_url: "https://www.kilikanoon.com.au/logo.png",
    founded_year: 1997,
    grapes: ["Shiraz", "Riesling", "Grenache"]
  },
  {
    name: "Taylors Wines (Wakefield)",
    legal_name: "Taylors Wines Pty Ltd",
    region: "Clare Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.taylorswines.com.au",
    logo_url: "https://www.taylorswines.com.au/logo.png",
    founded_year: 1969,
    grapes: ["Shiraz", "Cabernet Sauvignon", "Riesling"]
  },
  {
    name: "Pikes Wines",
    region: "Clare Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.pikeswines.com.au",
    logo_url: "https://www.pikeswines.com.au/logo.png",
    founded_year: 1984,
    grapes: ["Riesling", "Shiraz"]
  },
  {
    name: "Mount Horrocks",
    region: "Clare Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.mounthorrocks.com",
    logo_url: "https://www.mounthorrocks.com/logo.png",
    founded_year: 1982,
    grapes: ["Riesling", "Shiraz", "Semillon"]
  },
  {
    name: "Skillogalee",
    region: "Clare Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.skillogalee.com",
    logo_url: "https://www.skillogalee.com/logo.png",
    founded_year: 1970,
    grapes: ["Riesling", "Shiraz", "Cabernet Sauvignon"]
  },
  {
    name: "Pewsey Vale",
    region: "Eden Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.pewseyvale.com",
    logo_url: "https://www.pewseyvale.com/logo.png",
    founded_year: 1847,
    grapes: ["Riesling"]
  },
  {
    name: "Heggies Vineyard",
    region: "Eden Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.heggiesvineyard.com",
    logo_url: "https://www.heggiesvineyard.com/logo.png",
    founded_year: 1971,
    grapes: ["Riesling", "Chardonnay", "Viognier"]
  },
  {
    name: "Shaw + Smith",
    region: "Adelaide Hills",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.shawandsmith.com",
    logo_url: "https://www.shawandsmith.com/logo.png",
    founded_year: 1989,
    grapes: ["Sauvignon Blanc", "Chardonnay", "Shiraz", "Pinot Noir"]
  },
  {
    name: "Ashton Hills",
    region: "Adelaide Hills",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.ashtonhills.com.au",
    logo_url: "https://www.ashtonhills.com.au/logo.png",
    founded_year: 1982,
    grapes: ["Pinot Noir", "Riesling"]
  },
  {
    name: "The Lane Vineyard",
    region: "Adelaide Hills",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.thelane.com.au",
    logo_url: "https://www.thelane.com.au/logo.png",
    founded_year: 1993,
    grapes: ["Chardonnay", "Shiraz", "Sauvignon Blanc"]
  },
  {
    name: "Bird in Hand",
    region: "Adelaide Hills",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.birdinhand.com.au",
    logo_url: "https://www.birdinhand.com.au/logo.png",
    founded_year: 1997,
    grapes: ["Chardonnay", "Shiraz", "Pinot Noir"]
  },
  {
    name: "Petaluma",
    region: "Adelaide Hills",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.petaluma.com.au",
    logo_url: "https://www.petaluma.com.au/logo.png",
    founded_year: 1976,
    grapes: ["Chardonnay", "Riesling", "Shiraz"]
  },
  {
    name: "Wynns Coonawarra Estate",
    region: "Coonawarra",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.wynns.com.au",
    logo_url: "https://www.wynns.com.au/logo.png",
    founded_year: 1891,
    grapes: ["Cabernet Sauvignon", "Shiraz", "Riesling"]
  },
  {
    name: "Katnook Estate",
    region: "Coonawarra",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.katnookestate.com",
    logo_url: "https://www.katnookestate.com/logo.png",
    founded_year: 1979,
    grapes: ["Cabernet Sauvignon", "Shiraz", "Chardonnay"]
  },
  {
    name: "Parker Coonawarra Estate",
    region: "Coonawarra",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.parkercoonawarraestate.com.au",
    logo_url: "https://www.parkercoonawarraestate.com.au/logo.png",
    founded_year: 1985,
    grapes: ["Cabernet Sauvignon"]
  },
  {
    name: "Balnaves of Coonawarra",
    region: "Coonawarra",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.balnaves.com.au",
    logo_url: "https://www.balnaves.com.au/logo.png",
    founded_year: 1975,
    grapes: ["Cabernet Sauvignon", "Shiraz"]
  },
  {
    name: "Leconfield",
    region: "Coonawarra",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.leconfieldwines.com",
    logo_url: "https://www.leconfieldwines.com/logo.png",
    founded_year: 1974,
    grapes: ["Cabernet Sauvignon", "Shiraz", "Riesling"]
  },
  {
    name: "Cullen Wines",
    region: "Margaret River",
    state: "Western Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.cullenwines.com.au",
    logo_url: "https://www.cullenwines.com.au/logo.png",
    founded_year: 1971,
    grapes: ["Cabernet Sauvignon", "Sauvignon Blanc", "Chardonnay", "Semillon"]
  },
  {
    name: "Vasse Felix",
    region: "Margaret River",
    state: "Western Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.vassefelix.com.au",
    logo_url: "https://www.vassefelix.com.au/logo.png",
    founded_year: 1967,
    grapes: ["Cabernet Sauvignon", "Chardonnay", "Shiraz"]
  },
  {
    name: "Leeuwin Estate",
    region: "Margaret River",
    state: "Western Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.leeuwinestate.com.au",
    logo_url: "https://www.leeuwinestate.com.au/logo.png",
    founded_year: 1974,
    grapes: ["Chardonnay", "Cabernet Sauvignon", "Riesling"]
  },
  {
    name: "Moss Wood",
    region: "Margaret River",
    state: "Western Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.mosswood.com.au",
    logo_url: "https://www.mosswood.com.au/logo.png",
    founded_year: 1969,
    grapes: ["Cabernet Sauvignon", "Semillon", "Chardonnay"]
  },
  {
    name: "Voyager Estate",
    region: "Margaret River",
    state: "Western Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.voyagerestate.com.au",
    logo_url: "https://www.voyagerestate.com.au/logo.png",
    founded_year: 1978,
    grapes: ["Chardonnay", "Cabernet Sauvignon", "Sauvignon Blanc"]
  },
  {
    name: "Woodlands",
    region: "Margaret River",
    state: "Western Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.woodlandswines.com",
    logo_url: "https://www.woodlandswines.com/logo.png",
    founded_year: 1973,
    grapes: ["Cabernet Sauvignon", "Merlot"]
  },
  {
    name: "Xanadu Wines",
    region: "Margaret River",
    state: "Western Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.xanaduwines.com",
    logo_url: "https://www.xanaduwines.com/logo.png",
    founded_year: 1977,
    grapes: ["Cabernet Sauvignon", "Chardonnay", "Sauvignon Blanc"]
  },
  {
    name: "Fraser Gallop Estate",
    region: "Margaret River",
    state: "Western Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.frasergallop.com.au",
    logo_url: "https://www.frasergallop.com.au/logo.png",
    founded_year: 1999,
    grapes: ["Cabernet Sauvignon", "Chardonnay"]
  },
  {
    name: "Pierro",
    region: "Margaret River",
    state: "Western Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.pierro.com.au",
    logo_url: "https://www.pierro.com.au/logo.png",
    founded_year: 1979,
    grapes: ["Chardonnay", "Cabernet Sauvignon", "Semillon"]
  },
  {
    name: "Cape Mentelle",
    region: "Margaret River",
    state: "Western Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.capementelle.com.au",
    logo_url: "https://www.capementelle.com.au/logo.png",
    founded_year: 1970,
    grapes: ["Cabernet Sauvignon", "Shiraz", "Sauvignon Blanc"]
  },
  {
    name: "Howard Park",
    region: "Margaret River / Great Southern",
    state: "Western Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.howardparkwines.com.au",
    logo_url: "https://www.howardparkwines.com.au/logo.png",
    founded_year: 1986,
    grapes: ["Riesling", "Cabernet Sauvignon", "Chardonnay"]
  },
  {
    name: "Plantagenet Wines",
    region: "Great Southern",
    state: "Western Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.plantagenetwines.com",
    logo_url: "https://www.plantagenetwines.com/logo.png",
    founded_year: 1974,
    grapes: ["Riesling", "Shiraz", "Cabernet Sauvignon"]
  },
  {
    name: "Domaine Naturaliste",
    region: "Margaret River",
    state: "Western Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.domainenaturaliste.com",
    logo_url: "https://www.domainenaturaliste.com/logo.png",
    founded_year: 2007,
    grapes: ["Cabernet Sauvignon", "Chardonnay", "Syrah"]
  },
  {
    name: "Giaconda",
    region: "Beechworth",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.giaconda.com.au",
    logo_url: "https://www.giaconda.com.au/logo.png",
    founded_year: 1985,
    grapes: ["Chardonnay", "Shiraz", "Pinot Noir"]
  },
  {
    name: "Yering Station",
    region: "Yarra Valley",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.yering.com",
    logo_url: "https://www.yering.com/logo.png",
    founded_year: 1838,
    grapes: ["Chardonnay", "Pinot Noir", "Shiraz"]
  },
  {
    name: "Mount Mary",
    region: "Yarra Valley",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.mountmary.com.au",
    logo_url: "https://www.mountmary.com.au/logo.png",
    founded_year: 1971,
    grapes: ["Cabernet Sauvignon", "Chardonnay", "Pinot Noir"]
  },
  {
    name: "Yarra Yering",
    region: "Yarra Valley",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.yarrayering.com",
    logo_url: "https://www.yarrayering.com/logo.png",
    founded_year: 1969,
    grapes: ["Cabernet Sauvignon", "Shiraz", "Pinot Noir"]
  },
  {
    name: "De Bortoli",
    legal_name: "De Bortoli Wines Pty Ltd",
    region: "Yarra Valley / Riverina",
    state: "Victoria / New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.debortoli.com.au",
    logo_url: "https://www.debortoli.com.au/logo.png",
    founded_year: 1928,
    grapes: ["Chardonnay", "Pinot Noir", "Semillon", "Shiraz"]
  },
  {
    name: "Coldstream Hills",
    region: "Yarra Valley",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.coldstreamhills.com.au",
    logo_url: "https://www.coldstreamhills.com.au/logo.png",
    founded_year: 1985,
    grapes: ["Chardonnay", "Pinot Noir"]
  },
  {
    name: "Oakridge Wines",
    region: "Yarra Valley",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.oakridgewines.com.au",
    logo_url: "https://www.oakridgewines.com.au/logo.png",
    founded_year: 1978,
    grapes: ["Chardonnay", "Pinot Noir", "Cabernet Sauvignon"]
  },
  {
    name: "Giant Steps",
    region: "Yarra Valley",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.giantstepswine.com.au",
    logo_url: "https://www.giantstepswine.com.au/logo.png",
    founded_year: 1997,
    grapes: ["Chardonnay", "Pinot Noir"]
  },
  {
    name: "TarraWarra Estate",
    region: "Yarra Valley",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.tarrawarra.com.au",
    logo_url: "https://www.tarrawarra.com.au/logo.png",
    founded_year: 1983,
    grapes: ["Chardonnay", "Pinot Noir", "Shiraz"]
  },
  {
    name: "Mac Forbes",
    region: "Yarra Valley",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.macforbes.com",
    logo_url: "https://www.macforbes.com/logo.png",
    founded_year: 2004,
    grapes: ["Pinot Noir", "Chardonnay", "Riesling"]
  },
  {
    name: "Tahbilk",
    region: "Nagambie Lakes",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.tahbilk.com.au",
    logo_url: "https://www.tahbilk.com.au/logo.png",
    founded_year: 1860,
    grapes: ["Shiraz", "Marsanne", "Cabernet Sauvignon"]
  },
  {
    name: "Mitchelton",
    region: "Nagambie Lakes",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.mitchelton.com.au",
    logo_url: "https://www.mitchelton.com.au/logo.png",
    founded_year: 1969,
    grapes: ["Marsanne", "Shiraz", "Cabernet Sauvignon"]
  },
  {
    name: "Jasper Hill",
    region: "Heathcote",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.jasperhillwine.com.au",
    logo_url: "https://www.jasperhillwine.com.au/logo.png",
    founded_year: 1975,
    grapes: ["Shiraz", "Cabernet Sauvignon"]
  },
  {
    name: "Brown Brothers",
    legal_name: "Brown Brothers Milawa Vineyard Pty Ltd",
    region: "King Valley",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.brownbrothers.com.au",
    logo_url: "https://www.brownbrothers.com.au/logo.png",
    founded_year: 1889,
    grapes: ["Shiraz", "Chardonnay", "Riesling", "Prosecco (Glera)"]
  },
  {
    name: "Campbells Wines",
    region: "Rutherglen",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.campbellswines.com.au",
    logo_url: "https://www.campbellswines.com.au/logo.png",
    founded_year: 1870,
    grapes: ["Shiraz", "Muscat", "Durif"]
  },
  {
    name: "All Saints Estate",
    region: "Rutherglen",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.allsaintswine.com.au",
    logo_url: "https://www.allsaintswine.com.au/logo.png",
    founded_year: 1864,
    grapes: ["Shiraz", "Muscat", "Durif"]
  },
  {
    name: "Stanton & Killeen",
    region: "Rutherglen",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.stantonandkilleenwines.com.au",
    logo_url: "https://www.stantonandkilleenwines.com.au/logo.png",
    founded_year: 1875,
    grapes: ["Shiraz", "Durif", "Muscat"]
  },
  {
    name: "Bindi Wines",
    region: "Macedon Ranges",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.bindiwines.com.au",
    logo_url: "https://www.bindiwines.com.au/logo.png",
    founded_year: 1988,
    grapes: ["Pinot Noir", "Chardonnay"]
  },
  {
    name: "Paringa Estate",
    region: "Mornington Peninsula",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.paringaestate.com.au",
    logo_url: "https://www.paringaestate.com.au/logo.png",
    founded_year: 1985,
    grapes: ["Pinot Noir", "Chardonnay", "Shiraz"]
  },
  {
    name: "Ten Minutes by Tractor",
    region: "Mornington Peninsula",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.tenminutesbytractor.com.au",
    logo_url: "https://www.tenminutesbytractor.com.au/logo.png",
    founded_year: 1999,
    grapes: ["Pinot Noir", "Chardonnay"]
  },
  {
    name: "Kooyong",
    region: "Mornington Peninsula",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.kooyong.com",
    logo_url: "https://www.kooyong.com/logo.png",
    founded_year: 1996,
    grapes: ["Pinot Noir", "Chardonnay"]
  },
  {
    name: "Moorooduc Estate",
    region: "Mornington Peninsula",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.moorooducestate.com.au",
    logo_url: "https://www.moorooducestate.com.au/logo.png",
    founded_year: 1983,
    grapes: ["Pinot Noir", "Chardonnay"]
  },
  {
    name: "Main Ridge Estate",
    region: "Mornington Peninsula",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.mre.com.au",
    logo_url: "https://www.mre.com.au/logo.png",
    founded_year: 1975,
    grapes: ["Pinot Noir", "Chardonnay"]
  },
  {
    name: "Tyrrell's Wines",
    region: "Hunter Valley",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.tyrrells.com.au",
    logo_url: "https://www.tyrrells.com.au/logo.png",
    founded_year: 1858,
    grapes: ["Semillon", "Shiraz", "Chardonnay"]
  },
  {
    name: "Brokenwood Wines",
    region: "Hunter Valley",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.brokenwood.com.au",
    logo_url: "https://www.brokenwood.com.au/logo.png",
    founded_year: 1970,
    grapes: ["Semillon", "Shiraz", "Cabernet Sauvignon"]
  },
  {
    name: "Mount Pleasant (McWilliam's)",
    legal_name: "McWilliam's Wines Group Pty Ltd",
    region: "Hunter Valley",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.mountpleasantwines.com.au",
    logo_url: "https://www.mountpleasantwines.com.au/logo.png",
    founded_year: 1880,
    grapes: ["Semillon", "Shiraz"]
  },
  {
    name: "Tulloch",
    region: "Hunter Valley",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.tullochwines.com",
    logo_url: "https://www.tullochwines.com/logo.png",
    founded_year: 1895,
    grapes: ["Semillon", "Shiraz"]
  },
  {
    name: "Lake's Folly",
    region: "Hunter Valley",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.lakesfolly.com.au",
    logo_url: "https://www.lakesfolly.com.au/logo.png",
    founded_year: 1963,
    grapes: ["Cabernet Sauvignon", "Chardonnay"]
  },
  {
    name: "Clonakilla",
    region: "Canberra District",
    state: "New South Wales / ACT",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.clonakilla.com.au",
    logo_url: "https://www.clonakilla.com.au/logo.png",
    founded_year: 1971,
    grapes: ["Shiraz", "Viognier", "Riesling"]
  },
  {
    name: "Mount Majura Vineyard",
    region: "Canberra District",
    state: "Australian Capital Territory",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.mountmajura.com.au",
    logo_url: "https://www.mountmajura.com.au/logo.png",
    founded_year: 1988,
    grapes: ["Tempranillo", "Riesling", "Shiraz"]
  },
  {
    name: "Freycinet Vineyard",
    region: "East Coast Tasmania",
    state: "Tasmania",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.freycinetvineyard.com.au",
    logo_url: "https://www.freycinetvineyard.com.au/logo.png",
    founded_year: 1980,
    grapes: ["Pinot Noir", "Chardonnay", "Riesling"]
  },
  {
    name: "Josef Chromy Wines",
    region: "Tamar Valley",
    state: "Tasmania",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.josefchromy.com.au",
    logo_url: "https://www.josefchromy.com.au/logo.png",
    founded_year: 2004,
    grapes: ["Pinot Noir", "Chardonnay", "Riesling"]
  },
  {
    name: "Bay of Fires",
    region: "North East Tasmania",
    state: "Tasmania",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.bayoffireswines.com.au",
    logo_url: "https://www.bayoffireswines.com.au/logo.png",
    founded_year: 2001,
    grapes: ["Pinot Noir", "Chardonnay", "Sparkling blend"]
  },
  {
    name: "Tolpuddle Vineyard",
    region: "Coal River Valley",
    state: "Tasmania",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.tolpuddlevineyard.com",
    logo_url: "https://www.tolpuddlevineyard.com/logo.png",
    founded_year: 2011,
    grapes: ["Chardonnay", "Pinot Noir"]
  },
  {
    name: "Stefano Lubiana",
    region: "Derwent Valley",
    state: "Tasmania",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.slw.com.au",
    logo_url: "https://www.slw.com.au/logo.png",
    founded_year: 1990,
    grapes: ["Pinot Noir", "Chardonnay", "Sparkling blend"]
  },
  {
    name: "Domaine A",
    region: "Coal River Valley",
    state: "Tasmania",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.domaine-a.com.au",
    logo_url: "https://www.domaine-a.com.au/logo.png",
    founded_year: 1973,
    grapes: ["Cabernet Sauvignon", "Pinot Noir"]
  },
  {
    name: "Pooley Wines",
    region: "Coal River Valley",
    state: "Tasmania",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.pooleywines.com.au",
    logo_url: "https://www.pooleywines.com.au/logo.png",
    founded_year: 1985,
    grapes: ["Riesling", "Pinot Noir", "Chardonnay"]
  },
  {
    name: "Best's Wines",
    region: "Great Western",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.bestswines.com",
    logo_url: "https://www.bestswines.com/logo.png",
    founded_year: 1866,
    grapes: ["Shiraz", "Riesling", "Cabernet Sauvignon"]
  },
  {
    name: "Seppelt",
    region: "Grampians",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.seppelt.com.au",
    logo_url: "https://www.seppelt.com.au/logo.png",
    founded_year: 1851,
    grapes: ["Shiraz", "Sparkling Shiraz"]
  },
  {
    name: "Craiglee",
    region: "Sunbury",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.craiglee.com.au",
    logo_url: "https://www.craiglee.com.au/logo.png",
    founded_year: 1976,
    grapes: ["Shiraz"]
  },
  {
    name: "Bannockburn Vineyards",
    region: "Geelong",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.bannockburnvineyards.com",
    logo_url: "https://www.bannockburnvineyards.com/logo.png",
    founded_year: 1974,
    grapes: ["Pinot Noir", "Chardonnay", "Shiraz"]
  },
  {
    name: "Scotchmans Hill",
    region: "Geelong",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.scotchmanshill.com.au",
    logo_url: "https://www.scotchmanshill.com.au/logo.png",
    founded_year: 1982,
    grapes: ["Pinot Noir", "Chardonnay"]
  },
  {
    name: "Punt Road Wines",
    region: "Yarra Valley",
    state: "Victoria",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.puntroad.com.au",
    logo_url: "https://www.puntroad.com.au/logo.png",
    founded_year: 2000,
    grapes: ["Pinot Noir", "Chardonnay", "Cabernet Sauvignon"]
  },
  {
    name: "De Iuliis",
    region: "Hunter Valley",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.dewine.com.au",
    logo_url: "https://www.dewine.com.au/logo.png",
    founded_year: 1990,
    grapes: ["Semillon", "Shiraz"]
  },
  {
    name: "Audrey Wilkinson",
    region: "Hunter Valley",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.audreywilkinson.com.au",
    logo_url: "https://www.audreywilkinson.com.au/logo.png",
    founded_year: 1866,
    grapes: ["Semillon", "Shiraz"]
  },
  {
    name: "Margan Wines",
    region: "Hunter Valley",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.margan.com.au",
    logo_url: "https://www.margan.com.au/logo.png",
    founded_year: 1997,
    grapes: ["Semillon", "Shiraz", "Barbera"]
  },
  {
    name: "Tempus Two",
    region: "Hunter Valley",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.tempustwo.com.au",
    logo_url: "https://www.tempustwo.com.au/logo.png",
    founded_year: 1997,
    grapes: ["Semillon", "Shiraz", "Verdelho"]
  },
  {
    name: "Thomas Wines",
    region: "Hunter Valley",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.thomaswines.com.au",
    logo_url: "https://www.thomaswines.com.au/logo.png",
    founded_year: 1997,
    grapes: ["Semillon", "Shiraz"]
  },
  {
    name: "Meerea Park",
    region: "Hunter Valley",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.meereapark.com.au",
    logo_url: "https://www.meereapark.com.au/logo.png",
    founded_year: 1991,
    grapes: ["Semillon", "Shiraz"]
  },
  {
    name: "Keith Tulloch Wine",
    region: "Hunter Valley",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.keithtullochwine.com.au",
    logo_url: "https://www.keithtullochwine.com.au/logo.png",
    founded_year: 1997,
    grapes: ["Semillon", "Shiraz"]
  },
  {
    name: "Scarborough Wine Co",
    region: "Hunter Valley",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.scarboroughwine.com.au",
    logo_url: "https://www.scarboroughwine.com.au/logo.png",
    founded_year: 1987,
    grapes: ["Chardonnay", "Semillon"]
  },
  {
    name: "Logan Wines",
    region: "Orange",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.loganwines.com.au",
    logo_url: "https://www.loganwines.com.au/logo.png",
    founded_year: 1997,
    grapes: ["Chardonnay", "Pinot Noir", "Shiraz"]
  },
  {
    name: "Printhie Wines",
    region: "Orange",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.printhiewines.com.au",
    logo_url: "https://www.printhiewines.com.au/logo.png",
    founded_year: 1996,
    grapes: ["Chardonnay", "Pinot Noir", "Shiraz"]
  },
  {
    name: "Robert Oatley Vineyards",
    region: "Mudgee",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.robertoatley.com.au",
    logo_url: "https://www.robertoatley.com.au/logo.png",
    founded_year: 2006,
    grapes: ["Chardonnay", "Shiraz", "Cabernet Sauvignon"]
  },
  {
    name: "Huntington Estate",
    region: "Mudgee",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.huntingtonestate.com.au",
    logo_url: "https://www.huntingtonestate.com.au/logo.png",
    founded_year: 1969,
    grapes: ["Shiraz", "Cabernet Sauvignon"]
  },
  {
    name: "Lowe Wines",
    region: "Mudgee",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.lowewine.com.au",
    logo_url: "https://www.lowewine.com.au/logo.png",
    founded_year: 1987,
    grapes: ["Shiraz", "Zinfandel"]
  },
  {
    name: "Nick O'Leary Wines",
    region: "Canberra District",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.nickolearywines.com.au",
    logo_url: "https://www.nickolearywines.com.au/logo.png",
    founded_year: 2005,
    grapes: ["Riesling", "Shiraz"]
  },
  {
    name: "Lark Hill",
    region: "Canberra District",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.larkhillwine.com.au",
    logo_url: "https://www.larkhillwine.com.au/logo.png",
    founded_year: 1978,
    grapes: ["Riesling", "Pinot Noir"]
  },
  {
    name: "Helm Wines",
    region: "Canberra District",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.helmwines.com.au",
    logo_url: "https://www.helmwines.com.au/logo.png",
    founded_year: 1973,
    grapes: ["Riesling", "Cabernet Sauvignon"]
  },
  {
    name: "Ravensworth",
    region: "Canberra District",
    state: "New South Wales",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.ravensworthwines.com.au",
    logo_url: "https://www.ravensworthwines.com.au/logo.png",
    founded_year: 2000,
    grapes: ["Shiraz", "Marsanne", "Sangiovese"]
  },
  {
    name: "Ngeringa",
    region: "Adelaide Hills",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.ngeringa.com",
    logo_url: "https://www.ngeringa.com/logo.png",
    founded_year: 2001,
    grapes: ["Syrah", "Pinot Noir", "Viognier"]
  },
  {
    name: "Deviation Road",
    region: "Adelaide Hills",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.deviationroad.com",
    logo_url: "https://www.deviationroad.com/logo.png",
    founded_year: 2004,
    grapes: ["Pinot Noir", "Chardonnay", "Sparkling blend"]
  },
  {
    name: "Nepenthe",
    region: "Adelaide Hills",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.nepenthe.com.au",
    logo_url: "https://www.nepenthe.com.au/logo.png",
    founded_year: 1994,
    grapes: ["Sauvignon Blanc", "Chardonnay", "Pinot Gris"]
  },
  {
    name: "Hahndorf Hill Winery",
    region: "Adelaide Hills",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.hahndorfhillwinery.com.au",
    logo_url: "https://www.hahndorfhillwinery.com.au/logo.png",
    founded_year: 2002,
    grapes: ["Gewürztraminer", "Blaufränkisch", "Grüner Veltliner"]
  },
  {
    name: "Barossa Valley Estate",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.bvestate.com.au",
    logo_url: "https://www.bvestate.com.au/logo.png",
    founded_year: 1985,
    grapes: ["Shiraz", "Cabernet Sauvignon"]
  },
  {
    name: "Bethany Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.bethany.com.au",
    logo_url: "https://www.bethany.com.au/logo.png",
    founded_year: 1977,
    grapes: ["Shiraz", "Grenache", "Riesling"]
  },
  {
    name: "Schild Estate",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.schildestate.com.au",
    logo_url: "https://www.schildestate.com.au/logo.png",
    founded_year: 1998,
    grapes: ["Shiraz", "Grenache"]
  },
  {
    name: "Saltram",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.saltramwines.com.au",
    logo_url: "https://www.saltramwines.com.au/logo.png",
    founded_year: 1859,
    grapes: ["Shiraz", "Cabernet Sauvignon"]
  },
  {
    name: "Hentley Farm",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.hentleyfarm.com.au",
    logo_url: "https://www.hentleyfarm.com.au/logo.png",
    founded_year: 1997,
    grapes: ["Shiraz", "Grenache", "Cabernet Sauvignon"]
  },
  {
    name: "Dutschke Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.dutschkewines.com",
    logo_url: "https://www.dutschkewines.com/logo.png",
    founded_year: 1990,
    grapes: ["Shiraz", "Grenache"]
  },
  {
    name: "First Drop Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.firstdropwines.com",
    logo_url: "https://www.firstdropwines.com/logo.png",
    founded_year: 2005,
    grapes: ["Shiraz", "Grenache", "Sangiovese"]
  },
  {
    name: "Thorn-Clarke Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.thornclarkewines.com",
    logo_url: "https://www.thornclarkewines.com/logo.png",
    founded_year: 1998,
    grapes: ["Shiraz", "Cabernet Sauvignon"]
  },
  {
    name: "Rusden Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.rusdenwines.com.au",
    logo_url: "https://www.rusdenwines.com.au/logo.png",
    founded_year: 1979,
    grapes: ["Shiraz", "Grenache", "Mourvèdre"]
  },
  {
    name: "Sons of Eden",
    region: "Barossa Valley / Eden Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.sonsofeden.com",
    logo_url: "https://www.sonsofeden.com/logo.png",
    founded_year: 2000,
    grapes: ["Shiraz", "Riesling", "Grenache"]
  },
  {
    name: "Cirillo Estate Wines",
    region: "Barossa Valley",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.cirilloestate.com",
    logo_url: "https://www.cirilloestate.com/logo.png",
    founded_year: 2002,
    grapes: ["Grenache", "Shiraz"]
  },
  {
    name: "Dandelion Vineyards",
    region: "Barossa Valley / McLaren Vale",
    state: "South Australia",
    country: "Australia",
    address: nil,
    email: nil,
    phone: nil,
    instagram: nil,
    facebook: nil,
    website: "https://www.dandelionvineyards.com.au",
    logo_url: "https://www.dandelionvineyards.com.au/logo.png",
    founded_year: 2009,
    grapes: ["Shiraz", "Grenache", "Riesling"]
  }
].freeze


ALL_PRODUCERS.each do |attrs|
  grape_names = attrs.delete(:grapes) || []

  producer = Producer.find_or_initialize_by(name: attrs[:name])
  producer.assign_attributes(attrs)
  producer.save!

   # MAKE  TO ASSOCIATE GRAPES WITH THE PRODUCER BASED ON THE GRAPE NAMES
   # MAKE THE ASSOCIATION BETWEEN THE PRODUCER AND THE GRAPES

  puts "Seeded producer: #{producer.name}"
end

puts "Done. Seeded #{ALL_PRODUCERS.size} producers."