// producers.js
// Australian wine producers catalogue.
//
// Shape: Producer -> Country -> State -> Region -> grapes.
//
// Data policy:
// - null means the value has not been verified and should not be displayed as fact.
// - logo_url points to the producer's official website where possible; it is not
//   a direct image URL. Resolve/download the logo only with permission.
// - Verify contact details before using them for outreach or production imports.
// - Includes established, boutique, and emerging producers.
//
// Note: "Pedlidis" was ambiguous in public Australian-wine results. The closest
// clearly identified result is Pavlidis Estate in Drama, Greece, so it has not
// been incorrectly added as an Australian producer. Search result data instead
// identified Raidis Estate in Coonawarra as an Australian producer. [web:28][web:31]

export const producers = [
  // South Australia — Barossa Valley and Eden Valley
  { name: "Penfolds", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.penfolds.com", logo_url: "https://www.penfolds.com", founded_year: 1844, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Cabernet Sauvignon", "Grenache", "Chardonnay"] },
  { name: "Henschke", legal_name: "C.A. Henschke & Co.", address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.henschke.com.au", logo_url: "https://www.henschke.com.au", founded_year: 1868, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Eden Valley", grapes: ["Shiraz", "Cabernet Sauvignon", "Riesling", "Semillon"] },
  { name: "Yalumba", legal_name: "S. Smith & Son Pty Ltd", address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.yalumba.com", logo_url: "https://www.yalumba.com", founded_year: 1849, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Viognier", "Cabernet Sauvignon", "Grenache"] },
  { name: "Torbreck Vintners", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.torbreck.com", logo_url: "https://www.torbreck.com", founded_year: 1994, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache", "Mourvèdre", "Viognier"] },
  { name: "Grant Burge", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.grantburgewines.com.au", logo_url: "https://www.grantburgewines.com.au", founded_year: 1988, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Cabernet Sauvignon", "Riesling"] },
  { name: "Peter Lehmann Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.peterlehmannwines.com", logo_url: "https://www.peterlehmannwines.com", founded_year: 1979, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Riesling", "Semillon", "Grenache"] },
  { name: "Rockford Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.rockfordwines.com.au", logo_url: "https://www.rockfordwines.com.au", founded_year: 1984, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache", "Semillon"] },
  { name: "Charles Melton Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.charlesmeltonwines.com.au", logo_url: "https://www.charlesmeltonwines.com.au", founded_year: 1984, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache", "Mourvèdre"] },
  { name: "Elderton Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://eldertonwines.com.au", logo_url: "https://eldertonwines.com.au", founded_year: 1982, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Cabernet Sauvignon"] },
  { name: "Chateau Tanunda", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.chateautanunda.com", logo_url: "https://www.chateautanunda.com", founded_year: 1890, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache", "Cabernet Sauvignon"] },
  { name: "St Hallett", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.sthallett.com.au", logo_url: "https://www.sthallett.com.au", founded_year: 1944, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache"] },
  { name: "Seppeltsfield", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://seppeltsfield.com.au", logo_url: "https://seppeltsfield.com.au", founded_year: 1851, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache", "Mourvèdre"] },
  { name: "Two Hands Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.twohandswines.com", logo_url: "https://www.twohandswines.com", founded_year: 1999, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache"] },
  { name: "Turkey Flat", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.turkeyflat.com.au", logo_url: "https://www.turkeyflat.com.au", founded_year: 1990, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache", "Mourvèdre"] },
  { name: "Langmeil Winery", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.langmeilwinery.com.au", logo_url: "https://www.langmeilwinery.com.au", founded_year: 1996, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache", "Cabernet Sauvignon"] },
  { name: "Kalleske", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.kalleske.com", logo_url: "https://www.kalleske.com", founded_year: 2004, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache", "Zinfandel"] },
  { name: "Spinifex Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.spinifexwines.com.au", logo_url: "https://www.spinifexwines.com.au", founded_year: 2001, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache", "Mourvèdre", "Cinsault"] },
  { name: "Teusner Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.teusner.com.au", logo_url: "https://www.teusner.com.au", founded_year: 2001, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache", "Mourvèdre"] },
  { name: "Glaetzer Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.glaetzer.com", logo_url: "https://www.glaetzer.com", founded_year: 1996, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache"] },
  { name: "Hentley Farm", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.hentleyfarm.com.au", logo_url: "https://www.hentleyfarm.com.au", founded_year: 1997, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache", "Cabernet Sauvignon"] },
  { name: "First Drop Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.firstdropwines.com", logo_url: "https://www.firstdropwines.com", founded_year: 2005, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Barossa Valley", grapes: ["Shiraz", "Grenache", "Sangiovese"] },
  { name: "Sons of Eden", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.sonsofeden.com", logo_url: "https://www.sonsofeden.com", founded_year: 2000, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Eden Valley", grapes: ["Shiraz", "Riesling", "Grenache"] },
  { name: "Pewsey Vale", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.pewseyvale.com", logo_url: "https://www.pewseyvale.com", founded_year: 1847, country: "Australia", state: "South Australia", region: "Barossa", sub_region: "Eden Valley", grapes: ["Riesling"] },

  // South Australia — McLaren Vale, Adelaide Hills, Clare Valley, Coonawarra
  { name: "d'Arenberg", legal_name: "d'Arenberg Pty Ltd", address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.darenberg.com.au", logo_url: "https://www.darenberg.com.au", founded_year: 1912, country: "Australia", state: "South Australia", region: "Fleurieu", sub_region: "McLaren Vale", grapes: ["Shiraz", "Grenache", "Chardonnay", "Cabernet Sauvignon"] },
  { name: "Wirra Wirra", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.wirrawirra.com", logo_url: "https://www.wirrawirra.com", founded_year: 1894, country: "Australia", state: "South Australia", region: "Fleurieu", sub_region: "McLaren Vale", grapes: ["Shiraz", "Cabernet Sauvignon", "Grenache"] },
  { name: "Chapel Hill", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.chapelhillwine.com.au", logo_url: "https://www.chapelhillwine.com.au", founded_year: 1979, country: "Australia", state: "South Australia", region: "Fleurieu", sub_region: "McLaren Vale", grapes: ["Shiraz", "Cabernet Sauvignon"] },
  { name: "Coriole", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.coriole.com", logo_url: "https://www.coriole.com", founded_year: 1967, country: "Australia", state: "South Australia", region: "Fleurieu", sub_region: "McLaren Vale", grapes: ["Shiraz", "Sangiovese", "Fiano"] },
  { name: "S.C. Pannell", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.pannell.com.au", logo_url: "https://www.pannell.com.au", founded_year: 2004, country: "Australia", state: "South Australia", region: "Fleurieu", sub_region: "McLaren Vale", grapes: ["Grenache", "Shiraz", "Nebbiolo", "Tempranillo"] },
  { name: "Yangarra Estate Vineyard", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.yangarra.com", logo_url: "https://www.yangarra.com", founded_year: 2000, country: "Australia", state: "South Australia", region: "Fleurieu", sub_region: "McLaren Vale", grapes: ["Grenache", "Shiraz", "Roussanne"] },
  { name: "Gemtree Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.gemtreewines.com", logo_url: "https://www.gemtreewines.com", founded_year: 1998, country: "Australia", state: "South Australia", region: "Fleurieu", sub_region: "McLaren Vale", grapes: ["Shiraz", "Grenache", "Cabernet Sauvignon"] },
  { name: "Kay Brothers", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.kaybrothersamerywines.com", logo_url: "https://www.kaybrothersamerywines.com", founded_year: 1890, country: "Australia", state: "South Australia", region: "Fleurieu", sub_region: "McLaren Vale", grapes: ["Shiraz", "Grenache"] },
  { name: "Clarendon Hills", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.clarendonhills.com.au", logo_url: "https://www.clarendonhills.com.au", founded_year: 1989, country: "Australia", state: "South Australia", region: "Fleurieu", sub_region: "McLaren Vale", grapes: ["Grenache", "Shiraz"] },
  { name: "Brash Higgins", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.brashhiggins.com", logo_url: "https://www.brashhiggins.com", founded_year: 2008, country: "Australia", state: "South Australia", region: "Fleurieu", sub_region: "McLaren Vale", grapes: ["Nero d'Avola", "Shiraz", "Grenache"] },
  { name: "Shaw + Smith", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.shawandsmith.com", logo_url: "https://www.shawandsmith.com", founded_year: 1989, country: "Australia", state: "South Australia", region: "Mount Lofty Ranges", sub_region: "Adelaide Hills", grapes: ["Sauvignon Blanc", "Chardonnay", "Shiraz", "Pinot Noir"] },
  { name: "The Lane Vineyard", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.thelane.com.au", logo_url: "https://www.thelane.com.au", founded_year: 1993, country: "Australia", state: "South Australia", region: "Mount Lofty Ranges", sub_region: "Adelaide Hills", grapes: ["Chardonnay", "Shiraz", "Sauvignon Blanc"] },
  { name: "Bird in Hand", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.birdinhand.com.au", logo_url: "https://www.birdinhand.com.au", founded_year: 1997, country: "Australia", state: "South Australia", region: "Mount Lofty Ranges", sub_region: "Adelaide Hills", grapes: ["Chardonnay", "Shiraz", "Pinot Noir"] },
  { name: "Petaluma", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.petaluma.com.au", logo_url: "https://www.petaluma.com.au", founded_year: 1976, country: "Australia", state: "South Australia", region: "Mount Lofty Ranges", sub_region: "Adelaide Hills", grapes: ["Chardonnay", "Riesling", "Shiraz"] },
  { name: "Ashton Hills", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.ashtonhills.com.au", logo_url: "https://www.ashtonhills.com.au", founded_year: 1982, country: "Australia", state: "South Australia", region: "Mount Lofty Ranges", sub_region: "Adelaide Hills", grapes: ["Pinot Noir", "Riesling"] },
  { name: "Deviation Road", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.deviationroad.com", logo_url: "https://www.deviationroad.com", founded_year: 2004, country: "Australia", state: "South Australia", region: "Mount Lofty Ranges", sub_region: "Adelaide Hills", grapes: ["Pinot Noir", "Chardonnay", "Sparkling wine"] },
  { name: "Hahndorf Hill Winery", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.hahndorfhillwinery.com.au", logo_url: "https://www.hahndorfhillwinery.com.au", founded_year: 2002, country: "Australia", state: "South Australia", region: "Mount Lofty Ranges", sub_region: "Adelaide Hills", grapes: ["Gewürztraminer", "Blaufränkisch", "Grüner Veltliner"] },
  { name: "Grosset Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.grosset.com.au", logo_url: "https://www.grosset.com.au", founded_year: 1981, country: "Australia", state: "South Australia", region: "Mount Lofty Ranges", sub_region: "Clare Valley", grapes: ["Riesling", "Pinot Noir", "Cabernet Sauvignon"] },
  { name: "Jim Barry Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.jimbarry.com", logo_url: "https://www.jimbarry.com", founded_year: 1959, country: "Australia", state: "South Australia", region: "Mount Lofty Ranges", sub_region: "Clare Valley", grapes: ["Shiraz", "Riesling", "Cabernet Sauvignon"] },
  { name: "Kilikanoon Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.kilikanoon.com.au", logo_url: "https://www.kilikanoon.com.au", founded_year: 1997, country: "Australia", state: "South Australia", region: "Mount Lofty Ranges", sub_region: "Clare Valley", grapes: ["Shiraz", "Riesling", "Grenache"] },
  { name: "Taylors Wines", legal_name: "Taylors Wines Pty Ltd", address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.taylorswines.com.au", logo_url: "https://www.taylorswines.com.au", founded_year: 1969, country: "Australia", state: "South Australia", region: "Mount Lofty Ranges", sub_region: "Clare Valley", grapes: ["Shiraz", "Cabernet Sauvignon", "Riesling"] },
  { name: "Pikes Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.pikeswines.com.au", logo_url: "https://www.pikeswines.com.au", founded_year: 1984, country: "Australia", state: "South Australia", region: "Mount Lofty Ranges", sub_region: "Clare Valley", grapes: ["Riesling", "Shiraz"] },
  { name: "Wynns Coonawarra Estate", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.wynns.com.au", logo_url: "https://www.wynns.com.au", founded_year: 1891, country: "Australia", state: "South Australia", region: "Limestone Coast", sub_region: "Coonawarra", grapes: ["Cabernet Sauvignon", "Shiraz", "Riesling"] },
  { name: "Katnook Estate", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.katnookestate.com", logo_url: "https://www.katnookestate.com", founded_year: 1979, country: "Australia", state: "South Australia", region: "Limestone Coast", sub_region: "Coonawarra", grapes: ["Cabernet Sauvignon", "Shiraz", "Chardonnay"] },
  { name: "Balnaves of Coonawarra", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.balnaves.com.au", logo_url: "https://www.balnaves.com.au", founded_year: 1975, country: "Australia", state: "South Australia", region: "Limestone Coast", sub_region: "Coonawarra", grapes: ["Cabernet Sauvignon", "Shiraz"] },
  { name: "Raidis Estate", legal_name: null, address: null, email: "steven@raidis.com.au", phone: "+61 488 165 170", instagram: null, facebook: null, website: "https://www.raidis.com.au", logo_url: "https://www.raidis.com.au", founded_year: 1990, country: "Australia", state: "South Australia", region: "Limestone Coast", sub_region: "Coonawarra", grapes: ["Cabernet Sauvignon", "Riesling", "Sauvignon Blanc", "Pinot Gris", "Merlot", "Shiraz"] },

  // Western Australia
  { name: "Vasse Felix", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.vassefelix.com.au", logo_url: "https://www.vassefelix.com.au", founded_year: 1967, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Margaret River", grapes: ["Cabernet Sauvignon", "Chardonnay", "Shiraz"] },
  { name: "Cullen Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.cullenwines.com.au", logo_url: "https://www.cullenwines.com.au", founded_year: 1971, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Margaret River", grapes: ["Cabernet Sauvignon", "Sauvignon Blanc", "Chardonnay", "Semillon"] },
  { name: "Leeuwin Estate", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.leeuwinestate.com.au", logo_url: "https://www.leeuwinestate.com.au", founded_year: 1974, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Margaret River", grapes: ["Chardonnay", "Cabernet Sauvignon", "Riesling"] },
  { name: "Moss Wood", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.mosswood.com.au", logo_url: "https://www.mosswood.com.au", founded_year: 1969, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Margaret River", grapes: ["Cabernet Sauvignon", "Semillon", "Chardonnay"] },
  { name: "Voyager Estate", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.voyagerestate.com.au", logo_url: "https://www.voyagerestate.com.au", founded_year: 1978, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Margaret River", grapes: ["Chardonnay", "Cabernet Sauvignon", "Sauvignon Blanc"] },
  { name: "Woodlands Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.woodlandswines.com", logo_url: "https://www.woodlandswines.com", founded_year: 1973, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Margaret River", grapes: ["Cabernet Sauvignon", "Merlot"] },
  { name: "Xanadu Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.xanaduwines.com", logo_url: "https://www.xanaduwines.com", founded_year: 1977, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Margaret River", grapes: ["Cabernet Sauvignon", "Chardonnay", "Sauvignon Blanc"] },
  { name: "Fraser Gallop Estate", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.frasergallop.com.au", logo_url: "https://www.frasergallop.com.au", founded_year: 1999, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Margaret River", grapes: ["Cabernet Sauvignon", "Chardonnay"] },
  { name: "Pierro", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.pierro.com.au", logo_url: "https://www.pierro.com.au", founded_year: 1979, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Margaret River", grapes: ["Chardonnay", "Cabernet Sauvignon", "Semillon"] },
  { name: "Cape Mentelle", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.capementelle.com.au", logo_url: "https://www.capementelle.com.au", founded_year: 1970, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Margaret River", grapes: ["Cabernet Sauvignon", "Shiraz", "Sauvignon Blanc"] },
  { name: "Howard Park", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.howardparkwines.com.au", logo_url: "https://www.howardparkwines.com.au", founded_year: 1986, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Margaret River / Great Southern", grapes: ["Riesling", "Cabernet Sauvignon", "Chardonnay"] },
  { name: "Frankland Estate", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.franklandestate.com.au", logo_url: "https://www.franklandestate.com.au", founded_year: 1988, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Frankland River", grapes: ["Riesling", "Shiraz", "Cabernet Sauvignon"] },
  { name: "Plantagenet Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.plantagenetwines.com", logo_url: "https://www.plantagenetwines.com", founded_year: 1974, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Great Southern", grapes: ["Riesling", "Shiraz", "Cabernet Sauvignon"] },
  { name: "Domaine Naturaliste", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.domainenaturaliste.com", logo_url: "https://www.domainenaturaliste.com", founded_year: 2007, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Margaret River", grapes: ["Cabernet Sauvignon", "Chardonnay", "Syrah"] },
  { name: "Ashbrook Estate", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.ashbrookestate.com.au", logo_url: "https://www.ashbrookestate.com.au", founded_year: null, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Margaret River", grapes: ["Chardonnay", "Semillon", "Sauvignon Blanc"] },
  { name: "Ferngrove Vineyards", legal_name: "Ferngrove Vineyards Pty Ltd", address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.ferngrove.com.au", logo_url: "https://www.ferngrove.com.au", founded_year: null, country: "Australia", state: "Western Australia", region: "South West Australia", sub_region: "Great Southern", grapes: ["Riesling", "Shiraz", "Cabernet Sauvignon"] },

  // Victoria
  { name: "Giaconda", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.giaconda.com.au", logo_url: "https://www.giaconda.com.au", founded_year: 1985, country: "Australia", state: "Victoria", region: "North East Victoria", sub_region: "Beechworth", grapes: ["Chardonnay", "Shiraz", "Pinot Noir"] },
  { name: "Yering Station", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.yering.com", logo_url: "https://www.yering.com", founded_year: 1838, country: "Australia", state: "Victoria", region: "Port Phillip", sub_region: "Yarra Valley", grapes: ["Chardonnay", "Pinot Noir", "Shiraz"] },
  { name: "Mount Mary", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.mountmary.com.au", logo_url: "https://www.mountmary.com.au", founded_year: 1971, country: "Australia", state: "Victoria", region: "Port Phillip", sub_region: "Yarra Valley", grapes: ["Cabernet Sauvignon", "Chardonnay", "Pinot Noir"] },
  { name: "Yarra Yering", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.yarrayering.com", logo_url: "https://www.yarrayering.com", founded_year: 1969, country: "Australia", state: "Victoria", region: "Port Phillip", sub_region: "Yarra Valley", grapes: ["Cabernet Sauvignon", "Shiraz", "Pinot Noir"] },
  { name: "Coldstream Hills", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.coldstreamhills.com.au", logo_url: "https://www.coldstreamhills.com.au", founded_year: 1985, country: "Australia", state: "Victoria", region: "Port Phillip", sub_region: "Yarra Valley", grapes: ["Chardonnay", "Pinot Noir"] },
  { name: "Oakridge Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.oakridgewines.com.au", logo_url: "https://www.oakridgewines.com.au", founded_year: 1978, country: "Australia", state: "Victoria", region: "Port Phillip", sub_region: "Yarra Valley", grapes: ["Chardonnay", "Pinot Noir", "Cabernet Sauvignon"] },
  { name: "Giant Steps", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.giantstepswine.com.au", logo_url: "https://www.giantstepswine.com.au", founded_year: 1997, country: "Australia", state: "Victoria", region: "Port Phillip", sub_region: "Yarra Valley", grapes: ["Chardonnay", "Pinot Noir"] },
  { name: "TarraWarra Estate", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.tarrawarra.com.au", logo_url: "https://www.tarrawarra.com.au", founded_year: 1983, country: "Australia", state: "Victoria", region: "Port Phillip", sub_region: "Yarra Valley", grapes: ["Chardonnay", "Pinot Noir", "Shiraz"] },
  { name: "Mac Forbes", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.macforbes.com", logo_url: "https://www.macforbes.com", founded_year: 2004, country: "Australia", state: "Victoria", region: "Port Phillip", sub_region: "Yarra Valley", grapes: ["Pinot Noir", "Chardonnay", "Riesling"] },
  { name: "Bindi Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.bindiwines.com.au", logo_url: "https://www.bindiwines.com.au", founded_year: 1988, country: "Australia", state: "Victoria", region: "Port Phillip", sub_region: "Macedon Ranges", grapes: ["Pinot Noir", "Chardonnay"] },
  { name: "Jasper Hill", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.jasperhillwine.com.au", logo_url: "https://www.jasperhillwine.com.au", founded_year: 1975, country: "Australia", state: "Victoria", region: "Central Victoria", sub_region: "Heathcote", grapes: ["Shiraz", "Cabernet Sauvignon"] },
  { name: "Tahbilk", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.tahbilk.com.au", logo_url: "https://www.tahbilk.com.au", founded_year: 1860, country: "Australia", state: "Victoria", region: "Central Victoria", sub_region: "Nagambie Lakes", grapes: ["Shiraz", "Marsanne", "Cabernet Sauvignon"] },
  { name: "Brown Brothers", legal_name: "Brown Brothers Milawa Vineyard Pty Ltd", address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.brownbrothers.com.au", logo_url: "https://www.brownbrothers.com.au", founded_year: 1889, country: "Australia", state: "Victoria", region: "North East Victoria", sub_region: "King Valley", grapes: ["Shiraz", "Chardonnay", "Riesling", "Glera"] },
  { name: "Campbells Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.campbellswines.com.au", logo_url: "https://www.campbellswines.com.au", founded_year: 1870, country: "Australia", state: "Victoria", region: "North East Victoria", sub_region: "Rutherglen", grapes: ["Shiraz", "Muscat", "Durif"] },
  { name: "All Saints Estate", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.allsaintswine.com.au", logo_url: "https://www.allsaintswine.com.au", founded_year: 1864, country: "Australia", state: "Victoria", region: "North East Victoria", sub_region: "Rutherglen", grapes: ["Shiraz", "Muscat", "Durif"] },
  { name: "Stanton & Killeen", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.stantonandkilleenwines.com.au", logo_url: "https://www.stantonandkilleenwines.com.au", founded_year: 1875, country: "Australia", state: "Victoria", region: "North East Victoria", sub_region: "Rutherglen", grapes: ["Shiraz", "Durif", "Muscat"] },
  { name: "Bannockburn Vineyards", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.bannockburnvineyards.com", logo_url: "https://www.bannockburnvineyards.com", founded_year: 1974, country: "Australia", state: "Victoria", region: "Port Phillip", sub_region: "Geelong", grapes: ["Pinot Noir", "Chardonnay", "Shiraz"] },
  { name: "Scotchmans Hill", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.scotchmanshill.com.au", logo_url: "https://www.scotchmanshill.com.au", founded_year: 1982, country: "Australia", state: "Victoria", region: "Port Phillip", sub_region: "Geelong", grapes: ["Pinot Noir", "Chardonnay"] },
  { name: "Ten Minutes by Tractor", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.tenminutesbytractor.com.au", logo_url: "https://www.tenminutesbytractor.com.au", founded_year: 1999, country: "Australia", state: "Victoria", region: "Port Phillip", sub_region: "Mornington Peninsula", grapes: ["Pinot Noir", "Chardonnay"] },
  { name: "Kooyong", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.kooyong.com", logo_url: "https://www.kooyong.com", founded_year: 1996, country: "Australia", state: "Victoria", region: "Port Phillip", sub_region: "Mornington Peninsula", grapes: ["Pinot Noir", "Chardonnay"] },

  // New South Wales and ACT
  { name: "Tyrrell's Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.tyrrells.com.au", logo_url: "https://www.tyrrells.com.au", founded_year: 1858, country: "Australia", state: "New South Wales", region: "Hunter Valley", sub_region: "Hunter", grapes: ["Semillon", "Shiraz", "Chardonnay"] },
  { name: "Brokenwood Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.brokenwood.com.au", logo_url: "https://www.brokenwood.com.au", founded_year: 1970, country: "Australia", state: "New South Wales", region: "Hunter Valley", sub_region: "Hunter", grapes: ["Semillon", "Shiraz", "Cabernet Sauvignon"] },
  { name: "Mount Pleasant", legal_name: "McWilliam's Wines Group Pty Ltd", address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.mountpleasantwines.com.au", logo_url: "https://www.mountpleasantwines.com.au", founded_year: 1880, country: "Australia", state: "New South Wales", region: "Hunter Valley", sub_region: "Hunter", grapes: ["Semillon", "Shiraz"] },
  { name: "Lake's Folly", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.lakesfolly.com.au", logo_url: "https://www.lakesfolly.com.au", founded_year: 1963, country: "Australia", state: "New South Wales", region: "Hunter Valley", sub_region: "Hunter", grapes: ["Cabernet Sauvignon", "Chardonnay"] },
  { name: "Audrey Wilkinson", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.audreywilkinson.com.au", logo_url: "https://www.audreywilkinson.com.au", founded_year: 1866, country: "Australia", state: "New South Wales", region: "Hunter Valley", sub_region: "Hunter", grapes: ["Semillon", "Shiraz"] },
  { name: "Thomas Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.thomaswines.com.au", logo_url: "https://www.thomaswines.com.au", founded_year: 1997, country: "Australia", state: "New South Wales", region: "Hunter Valley", sub_region: "Hunter", grapes: ["Semillon", "Shiraz"] },
  { name: "Margan Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.margan.com.au", logo_url: "https://www.margan.com.au", founded_year: 1997, country: "Australia", state: "New South Wales", region: "Hunter Valley", sub_region: "Hunter", grapes: ["Semillon", "Shiraz", "Barbera"] },
  { name: "Clonakilla", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.clonakilla.com.au", logo_url: "https://www.clonakilla.com.au", founded_year: 1971, country: "Australia", state: "Australian Capital Territory", region: "Southern New South Wales", sub_region: "Canberra District", grapes: ["Shiraz", "Viognier", "Riesling"] },
  { name: "Helm Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.helmwines.com.au", logo_url: "https://www.helmwines.com.au", founded_year: 1973, country: "Australia", state: "Australian Capital Territory", region: "Southern New South Wales", sub_region: "Canberra District", grapes: ["Riesling", "Cabernet Sauvignon"] },
  { name: "Logan Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.loganwines.com.au", logo_url: "https://www.loganwines.com.au", founded_year: 1997, country: "Australia", state: "New South Wales", region: "Central Ranges", sub_region: "Orange", grapes: ["Chardonnay", "Pinot Noir", "Shiraz"] },
  { name: "Printhie Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.printhiewines.com.au", logo_url: "https://www.printhiewines.com.au", founded_year: 1996, country: "Australia", state: "New South Wales", region: "Central Ranges", sub_region: "Orange", grapes: ["Chardonnay", "Pinot Noir", "Shiraz"] },
  { name: "Robert Oatley Vineyards", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.robertoatley.com.au", logo_url: "https://www.robertoatley.com.au", founded_year: 2006, country: "Australia", state: "New South Wales", region: "Central Ranges", sub_region: "Mudgee", grapes: ["Chardonnay", "Shiraz", "Cabernet Sauvignon"] },
  { name: "Lowe Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.lowewine.com.au", logo_url: "https://www.lowewine.com.au", founded_year: 1987, country: "Australia", state: "New South Wales", region: "Central Ranges", sub_region: "Mudgee", grapes: ["Shiraz", "Zinfandel"] },
  { name: "De Bortoli", legal_name: "De Bortoli Wines Pty Ltd", address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.debortoli.com.au", logo_url: "https://www.debortoli.com.au", founded_year: 1928, country: "Australia", state: "New South Wales", region: "Big Rivers", sub_region: "Riverina", grapes: ["Chardonnay", "Pinot Noir", "Semillon", "Shiraz"] },

  // Tasmania
  { name: "Josef Chromy Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.josefchromy.com.au", logo_url: "https://www.josefchromy.com.au", founded_year: 2004, country: "Australia", state: "Tasmania", region: "Tamar Valley", sub_region: "Tamar Valley", grapes: ["Pinot Noir", "Chardonnay", "Riesling"] },
  { name: "Tolpuddle Vineyard", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.tolpuddlevineyard.com", logo_url: "https://www.tolpuddlevineyard.com", founded_year: 1985, country: "Australia", state: "Tasmania", region: "Coal River Valley", sub_region: "Coal River Valley", grapes: ["Chardonnay", "Pinot Noir"] },
  { name: "Stefano Lubiana", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.slw.com.au", logo_url: "https://www.slw.com.au", founded_year: 1990, country: "Australia", state: "Tasmania", region: "Derwent Valley", sub_region: "Derwent Valley", grapes: ["Pinot Noir", "Chardonnay", "Sparkling wine"] },
  { name: "Pooley Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.pooleywines.com.au", logo_url: "https://www.pooleywines.com.au", founded_year: 1985, country: "Australia", state: "Tasmania", region: "Coal River Valley", sub_region: "Coal River Valley", grapes: ["Riesling", "Pinot Noir", "Chardonnay"] },
  { name: "Freycinet Vineyard", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.freycinetvineyard.com.au", logo_url: "https://www.freycinetvineyard.com.au", founded_year: 1980, country: "Australia", state: "Tasmania", region: "East Coast Tasmania", sub_region: "East Coast Tasmania", grapes: ["Pinot Noir", "Chardonnay", "Riesling"] },

  // Queensland and additional producers
  { name: "Ballandean Estate", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.ballandeanestate.com", logo_url: "https://www.ballandeanestate.com", founded_year: 1932, country: "Australia", state: "Queensland", region: "Granite Belt", sub_region: "Granite Belt", grapes: ["Shiraz", "Vermentino", "Viognier", "Chambourcin"] },
  { name: "Symphony Hill Wines", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.symphonyhill.com.au", logo_url: "https://www.symphonyhill.com.au", founded_year: null, country: "Australia", state: "Queensland", region: "Granite Belt", sub_region: "Granite Belt", grapes: ["Shiraz", "Chambourcin", "Verdelho"] },
  { name: "Golden Grove Estate", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.goldengroveestate.com.au", logo_url: "https://www.goldengroveestate.com.au", founded_year: null, country: "Australia", state: "Queensland", region: "Granite Belt", sub_region: "Granite Belt", grapes: ["Shiraz", "Verdelho", "Viognier"] },
  { name: "Savannah Estate", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.savannahestate.com.au", logo_url: "https://www.savannahestate.com.au", founded_year: null, country: "Australia", state: "Queensland", region: "Granite Belt", sub_region: "Granite Belt", grapes: ["Shiraz", "Viognier", "Verdelho"] },
  { name: "St Mary's Winery", legal_name: null, address: null, email: null, phone: null, instagram: null, facebook: null, website: "https://www.stmaryswinery.com.au", logo_url: "https://www.stmaryswinery.com.au", founded_year: null, country: "Australia", state: "Queensland", region: "Granite Belt", sub_region: "Granite Belt", grapes: ["Shiraz", "Chambourcin", "Verdelho"] },
];

export default producers;
